/**
 * Permission catalogue and role → permission mapping.
 * Every server action / route handler resolves against these codes; the UI only
 * mirrors them for affordance, it is never the enforcement point.
 */

export const PERMISSIONS = {
  // Finance — vouchers, tax, budget
  VOUCHER_VIEW: "voucher.view",
  VOUCHER_GENERATE: "voucher.generate",
  VOUCHER_SIGN: "voucher.sign",
  /// Signs any rung of the ladder, not only the one the holder's role names.
  VOUCHER_SIGN_ANY: "voucher.sign_any",
  TAX_VIEW: "tax.view",
  TAX_MANAGE: "tax.manage",
  TAX_VERIFY: "tax.verify",
  BUDGET_VIEW: "budget.view",
  BUDGET_MANAGE: "budget.manage",

  // Receiving exceptions
  VARIANCE_VIEW: "variance.view",
  VARIANCE_RESOLVE: "variance.resolve",
  RETURN_VIEW: "return.view",
  RETURN_CREATE: "return.create",
  RETURN_AUTHORISE: "return.authorise",

  // Work orders — ZAM/PUR/SOP-01 §4.6. Admin raises them, procurement supplies
  // the rate, and Internal Audit reviews the ones outside CPC's domain.
  // Build-outs — ZAM/PUR/SOP-01 Build-Outs section.
  BUILD_OUT_VIEW: "build_out.view",
  BUILD_OUT_CREATE: "build_out.create",
  BUILD_OUT_EDIT: "build_out.edit",
  /// BO-002 — management's go-ahead, which is not the same act as raising it.
  BUILD_OUT_MANAGEMENT_APPROVE: "build_out.management_approve",
  BUILD_OUT_TASK_UPDATE: "build_out.task_update",
  BUILD_OUT_MEETING_MANAGE: "build_out.meeting_manage",
  BUILD_OUT_CLOSE: "build_out.close",
  // Rental & Negotiation Committee.
  RNC_VIEW: "rnc.view",
  RNC_CASE_RAISE: "rnc.case_raise",
  RNC_DECIDE: "rnc.decide",
  RNC_MANAGE: "rnc.manage",
  WORK_ORDER_VIEW: "work_order.view",
  WORK_ORDER_CREATE: "work_order.create",
  WORK_ORDER_EDIT: "work_order.edit",
  WORK_ORDER_AUDIT_REVIEW: "work_order.audit_review",
  WORK_ORDER_APPROVE: "work_order.approve",
  WORK_ORDER_ISSUE: "work_order.issue",
  WORK_ORDER_CLOSE: "work_order.close",

  // Masters
  MASTER_VIEW: "masters.view",
  MASTER_MANAGE: "masters.manage",
  ASSET_INSURANCE_MANAGE: "asset.insurance_manage",

  // Requirements — the demand front door
  REQUIREMENT_VIEW: "requirements.view",
  REQUIREMENT_VIEW_ALL: "requirements.view_all",
  REQUIREMENT_CREATE: "requirements.create",
  REQUIREMENT_EDIT: "requirements.edit",
  REQUIREMENT_SUBMIT: "requirements.submit",
  REQUIREMENT_CHECK_STOCK: "requirements.check_stock",
  REQUIREMENT_DECIDE: "requirements.decide",
  REQUIREMENT_CANCEL: "requirements.cancel",

  // Store requisitions
  SR_VIEW: "store_requisition.view",
  SR_CREATE: "store_requisition.create",
  SR_APPROVE: "store_requisition.approve",
  SR_APPROVE_HOD: "store_requisition.approve_hod",
  SR_APPROVE_CROSS_STORE: "store_requisition.approve_cross_store",
  SR_ISSUE: "store_requisition.issue",
  INVENTORY_RESERVE: "inventory.reserve",

  // Requisitions
  PR_VIEW: "pr.view",
  PR_VIEW_ALL: "pr.view_all",
  PR_CREATE: "pr.create",
  PR_EDIT: "pr.edit",
  PR_SUBMIT: "pr.submit",
  PR_APPROVE: "pr.approve",
  PR_REJECT: "pr.reject",
  PR_RETURN: "pr.return",
  PR_CANCEL: "pr.cancel",
  PR_HOLD: "pr.hold",
  PR_CLARIFY: "pr.clarify",

  // Sourcing
  RFQ_VIEW: "rfq.view",
  RFQ_ISSUE: "rfq.issue",
  QUOTE_ENTER: "quote.enter",
  QUOTE_VIEW: "quote.view",
  COMPARATIVE_CREATE: "comparative.create",
  COMPARATIVE_VIEW: "comparative.view",
  /// The second signature on the Cost Analysis Form. Held separately from
  /// building the comparative, because a form checked only by its author is not
  /// checked at all.
  COMPARATIVE_VERIFY: "comparative.verify",
  NEGOTIATE: "negotiate.record",
  VENDOR_SELECT: "sourcing.select_vendor",

  // CPC
  CPC_VIEW: "cpc.view",
  /// Raises a case for the committee. Distinct from deciding one: procurement
  /// puts the case up, the committee resolves it.
  CPC_CASE_RAISE: "cpc.case_raise",
  CPC_DECIDE: "cpc.decide",
  /**
   * PC-023 — the Office of the CEO above the value tier.
   *
   * Deliberately not held by any committee role. The committee approving on
   * the CEO's behalf is the substitution the second approval exists to
   * prevent, and a permission both offices hold cannot tell the two apart.
   */
  CPC_CEO_APPROVE: "cpc.ceoApprove",
  CPC_MANAGE: "cpc.manage",

  // Purchase orders
  PO_VIEW: "po.view",
  PO_CREATE: "po.create",
  PO_EDIT: "po.edit",
  PO_APPROVE: "po.approve",
  PO_ISSUE: "po.issue",
  PO_CLOSE: "po.close",
  PO_CANCEL: "po.cancel",

  // Petty cash
  PETTY_CASH_VIEW: "petty_cash.view",
  PETTY_CASH_CREATE: "petty_cash.create",
  PETTY_CASH_EVALUATE: "petty_cash.evaluate",
  PETTY_CASH_APPROVE: "petty_cash.approve",
  PETTY_CASH_RECONCILE: "petty_cash.reconcile",

  // Operations
  GATE_PASS_VIEW: "gate_pass.view",
  GATE_PASS_CREATE: "gate_pass.create",
  RECEIVE_GOODS: "receiving.record",
  /// Confirms a service was performed. The services counterpart to recording a
  /// receipt, and the act that releases the vendor's invoice.
  SERVICE_ACCEPT: "service.accept",
  /// Confirms a service assigned to somebody else's point of contact. Held by
  /// the few who can act for a department that is unavailable.
  SERVICE_ACCEPT_ANY: "service.accept_any",
  RECEIVING_VIEW: "receiving.view",
  INSPECTION_VIEW: "inspection.view",
  INSPECTION_PERFORM: "inspection.perform",
  /// Books an inspection against a delivery. Separate from performing it, so
  /// receiving can raise one without being able to record its result.
  INSPECTION_SCHEDULE: "inspection.schedule",
  GRN_VIEW: "grn.view",
  GRN_CREATE: "grn.create",
  GRN_POST: "grn.post",
  GRN_CANCEL: "grn.cancel",

  // Stores & inventory
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_ADJUST: "inventory.adjust",
  STORE_ISSUE: "store.issue",
  STORE_ISSUE_APPROVE: "store.issue_approve",
  STORE_TRANSFER: "store.transfer",
  STORE_TRANSFER_APPROVE: "store.transfer_approve",
  STACKING_RECORD: "store.stacking",

  // Invoices & finance
  INVOICE_VIEW: "invoice.view",
  INVOICE_CREATE: "invoice.create",
  INVOICE_VERIFY: "invoice.verify",
  INVOICE_APPROVE: "invoice.approve",
  INVOICE_EXCEPTION_APPROVE: "invoice.exception_approve",
  FINANCE_HANDOFF: "finance.handoff",
  FINANCE_ACK: "finance.acknowledge",
  PAYMENT_RECORD: "finance.record_payment",

  // Vendors
  VENDOR_VIEW: "vendor.view",
  VENDOR_CREATE: "vendor.create",
  VENDOR_EDIT: "vendor.edit",
  VENDOR_EVALUATE: "vendor.evaluate",
  VENDOR_APPROVE: "vendor.approve",
  VENDOR_ISSUE_RAISE: "vendor.issue_raise",
  VENDOR_BLACKLIST: "vendor.blacklist",
  VENDOR_AUDIT_REVIEW: "vendor.audit_review",
  VENDOR_FINANCIALS_VIEW: "vendor.view_financials",

  // Assets & disposal
  ASSET_VIEW: "asset.view",
  ASSET_MANAGE: "asset.manage",
  DISPOSAL_VIEW: "disposal.view",
  DISPOSAL_CREATE: "disposal.create",
  DISPOSAL_APPROVE: "disposal.approve",
  DISPOSAL_AUDIT_REVIEW: "disposal.audit_review",
  DISPOSAL_MANAGEMENT_APPROVE: "disposal.management_approve",

  // Cross-cutting
  ANALYTICS_VIEW: "analytics.view",
  ANALYTICS_VIEW_ALL_ENTITIES: "analytics.view_all_entities",
  EXPORT_DATA: "data.export",
  AUDIT_VIEW: "audit.view",
  DOCUMENT_VIEW: "document.view",
  DOCUMENT_UPLOAD: "document.upload",
  DOCUMENT_VIEW_CONFIDENTIAL: "document.view_confidential",
  DOCUMENT_VIEW_RESTRICTED: "document.view_restricted",
  DOCUMENT_DELETE: "document.delete",
  EXCEPTION_VIEW: "exception.view",
  EXCEPTION_MANAGE: "exception.manage",

  // Administration
  CONFIG_MANAGE: "admin.config",
  USER_MANAGE: "admin.users",
  ROLE_MANAGE: "admin.roles",
  MASTER_DATA_MANAGE: "admin.master_data",
  APPROVAL_RULE_MANAGE: "admin.approval_rules",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

type PermMeta = { group: string; name: string };

export const PERMISSION_META: Record<string, PermMeta> = {
  [PERMISSIONS.VOUCHER_VIEW]: { group: "Finance", name: "View payment vouchers" },
  [PERMISSIONS.VOUCHER_GENERATE]: { group: "Finance", name: "Generate a payment voucher" },
  [PERMISSIONS.VOUCHER_SIGN]: { group: "Finance", name: "Sign a voucher at your own rung" },
  [PERMISSIONS.VOUCHER_SIGN_ANY]: { group: "Finance", name: "Sign any rung of the ladder" },
  [PERMISSIONS.TAX_VIEW]: { group: "Finance", name: "View tax rates and lines" },
  [PERMISSIONS.TAX_MANAGE]: { group: "Finance", name: "Maintain tax rates" },
  [PERMISSIONS.TAX_VERIFY]: { group: "Finance", name: "Verify tax on an invoice" },
  [PERMISSIONS.BUDGET_VIEW]: { group: "Finance", name: "View budgets and utilisation" },
  [PERMISSIONS.BUDGET_MANAGE]: { group: "Finance", name: "Maintain budget allocations" },
  [PERMISSIONS.VARIANCE_VIEW]: { group: "Receiving", name: "View receipt variances" },
  [PERMISSIONS.VARIANCE_RESOLVE]: { group: "Receiving", name: "Resolve a receipt variance" },
  [PERMISSIONS.RETURN_VIEW]: { group: "Receiving", name: "View vendor returns" },
  [PERMISSIONS.RETURN_CREATE]: { group: "Receiving", name: "Raise a vendor return" },
  [PERMISSIONS.RETURN_AUTHORISE]: { group: "Receiving", name: "Authorise a vendor return" },
  [PERMISSIONS.BUILD_OUT_VIEW]: { group: "Build-outs", name: "View build-outs" },
  [PERMISSIONS.BUILD_OUT_CREATE]: { group: "Build-outs", name: "Raise a build-out" },
  [PERMISSIONS.BUILD_OUT_EDIT]: { group: "Build-outs", name: "Edit a build-out" },
  [PERMISSIONS.BUILD_OUT_MANAGEMENT_APPROVE]: {
    group: "Build-outs",
    name: "Give management's go-ahead for a build-out",
  },
  [PERMISSIONS.BUILD_OUT_TASK_UPDATE]: { group: "Build-outs", name: "Update a checklist task" },
  [PERMISSIONS.BUILD_OUT_MEETING_MANAGE]: { group: "Build-outs", name: "Call and minute CFC meetings" },
  [PERMISSIONS.BUILD_OUT_CLOSE]: { group: "Build-outs", name: "Close a build-out" },
  [PERMISSIONS.RNC_VIEW]: { group: "RNC", name: "View rental committee cases" },
  [PERMISSIONS.RNC_CASE_RAISE]: { group: "RNC", name: "Raise a rental committee case" },
  [PERMISSIONS.RNC_DECIDE]: { group: "RNC", name: "Vote on a rental committee case" },
  [PERMISSIONS.RNC_MANAGE]: { group: "RNC", name: "Manage the rental committee roster and decisions" },
  [PERMISSIONS.WORK_ORDER_VIEW]: { group: "Work orders", name: "View work orders" },
  [PERMISSIONS.WORK_ORDER_CREATE]: { group: "Work orders", name: "Raise a work order" },
  [PERMISSIONS.WORK_ORDER_EDIT]: { group: "Work orders", name: "Edit a draft work order" },
  [PERMISSIONS.WORK_ORDER_AUDIT_REVIEW]: {
    group: "Work orders",
    name: "Internal Audit review of a work order",
  },
  [PERMISSIONS.WORK_ORDER_APPROVE]: { group: "Work orders", name: "Approve a work order" },
  [PERMISSIONS.WORK_ORDER_ISSUE]: { group: "Work orders", name: "Issue a work order to the vendor" },
  [PERMISSIONS.WORK_ORDER_CLOSE]: { group: "Work orders", name: "Complete or close a work order" },
  [PERMISSIONS.MASTER_VIEW]: { group: "Masters", name: "View master data" },
  [PERMISSIONS.MASTER_MANAGE]: { group: "Masters", name: "Maintain master data" },
  [PERMISSIONS.ASSET_INSURANCE_MANAGE]: { group: "Assets", name: "Maintain asset insurance" },
  [PERMISSIONS.REQUIREMENT_VIEW]: { group: "Requirements", name: "View own/department requirements" },
  [PERMISSIONS.REQUIREMENT_VIEW_ALL]: { group: "Requirements", name: "View all requirements" },
  [PERMISSIONS.REQUIREMENT_CREATE]: { group: "Requirements", name: "Raise a requirement" },
  [PERMISSIONS.REQUIREMENT_EDIT]: { group: "Requirements", name: "Edit a requirement" },
  [PERMISSIONS.REQUIREMENT_SUBMIT]: { group: "Requirements", name: "Submit a requirement" },
  [PERMISSIONS.REQUIREMENT_CHECK_STOCK]: { group: "Requirements", name: "Run the availability check" },
  [PERMISSIONS.REQUIREMENT_DECIDE]: { group: "Requirements", name: "Decide stock or procurement" },
  [PERMISSIONS.REQUIREMENT_CANCEL]: { group: "Requirements", name: "Cancel a requirement" },
  [PERMISSIONS.SR_VIEW]: { group: "Store requisitions", name: "View store requisitions" },
  [PERMISSIONS.SR_CREATE]: { group: "Store requisitions", name: "Raise a store requisition" },
  [PERMISSIONS.SR_APPROVE]: { group: "Store requisitions", name: "Approve a store requisition" },
  [PERMISSIONS.SR_APPROVE_HOD]: { group: "Store requisitions", name: "Approve as department head" },
  [PERMISSIONS.SR_APPROVE_CROSS_STORE]: { group: "Store requisitions", name: "Authorise cross-store fulfilment" },
  [PERMISSIONS.SR_ISSUE]: { group: "Store requisitions", name: "Issue against a store requisition" },
  [PERMISSIONS.INVENTORY_RESERVE]: { group: "Stores", name: "Reserve and release stock" },
  [PERMISSIONS.PR_VIEW]: { group: "Requisitions", name: "View own/department requisitions" },
  [PERMISSIONS.PR_VIEW_ALL]: { group: "Requisitions", name: "View all requisitions" },
  [PERMISSIONS.PR_CREATE]: { group: "Requisitions", name: "Create requisition" },
  [PERMISSIONS.PR_EDIT]: { group: "Requisitions", name: "Edit requisition" },
  [PERMISSIONS.PR_SUBMIT]: { group: "Requisitions", name: "Submit requisition" },
  [PERMISSIONS.PR_APPROVE]: { group: "Requisitions", name: "Approve requisition" },
  [PERMISSIONS.PR_REJECT]: { group: "Requisitions", name: "Reject requisition" },
  [PERMISSIONS.PR_RETURN]: { group: "Requisitions", name: "Return requisition" },
  [PERMISSIONS.PR_CANCEL]: { group: "Requisitions", name: "Cancel requisition" },
  [PERMISSIONS.PR_HOLD]: { group: "Requisitions", name: "Place requisition on hold" },
  [PERMISSIONS.PR_CLARIFY]: { group: "Requisitions", name: "Request clarification" },
  [PERMISSIONS.RFQ_VIEW]: { group: "Sourcing", name: "View RFQs" },
  [PERMISSIONS.RFQ_ISSUE]: { group: "Sourcing", name: "Create & issue RFQ" },
  [PERMISSIONS.QUOTE_ENTER]: { group: "Sourcing", name: "Enter vendor quotations" },
  [PERMISSIONS.QUOTE_VIEW]: { group: "Sourcing", name: "View quotations" },
  [PERMISSIONS.COMPARATIVE_CREATE]: { group: "Sourcing", name: "Build comparative analysis" },
  [PERMISSIONS.COMPARATIVE_VIEW]: { group: "Sourcing", name: "View comparatives" },
  [PERMISSIONS.COMPARATIVE_VERIFY]: { group: "Sourcing", name: "Verify cost analysis form" },
  [PERMISSIONS.NEGOTIATE]: { group: "Sourcing", name: "Record negotiation rounds" },
  [PERMISSIONS.VENDOR_SELECT]: { group: "Sourcing", name: "Select awarded vendor" },
  [PERMISSIONS.CPC_VIEW]: { group: "CPC", name: "View CPC cases" },
  [PERMISSIONS.CPC_CASE_RAISE]: { group: "CPC", name: "Raise a case for the committee" },
  [PERMISSIONS.CPC_DECIDE]: { group: "CPC", name: "Cast CPC decision" },
  [PERMISSIONS.CPC_CEO_APPROVE]: {
    group: "CPC",
    name: "Approve as the Office of the CEO (above the value tier)",
  },
  [PERMISSIONS.CPC_MANAGE]: { group: "CPC", name: "Manage CPC meetings & agenda" },
  [PERMISSIONS.PO_VIEW]: { group: "Purchase Orders", name: "View purchase orders" },
  [PERMISSIONS.PO_CREATE]: { group: "Purchase Orders", name: "Create purchase order" },
  [PERMISSIONS.PO_EDIT]: { group: "Purchase Orders", name: "Edit purchase order" },
  [PERMISSIONS.PO_APPROVE]: { group: "Purchase Orders", name: "Approve purchase order" },
  [PERMISSIONS.PO_ISSUE]: { group: "Purchase Orders", name: "Issue purchase order to vendor" },
  [PERMISSIONS.PO_CLOSE]: { group: "Purchase Orders", name: "Close purchase order" },
  [PERMISSIONS.PO_CANCEL]: { group: "Purchase Orders", name: "Cancel purchase order" },
  [PERMISSIONS.PETTY_CASH_VIEW]: { group: "Petty Cash", name: "View petty cash requests" },
  [PERMISSIONS.PETTY_CASH_CREATE]: { group: "Petty Cash", name: "Raise petty cash request" },
  [PERMISSIONS.PETTY_CASH_EVALUATE]: { group: "Petty Cash", name: "Evaluate & record market quotes" },
  [PERMISSIONS.PETTY_CASH_APPROVE]: { group: "Petty Cash", name: "Approve cash purchase / voucher" },
  [PERMISSIONS.PETTY_CASH_RECONCILE]: { group: "Petty Cash", name: "Reconcile petty cash" },
  [PERMISSIONS.GATE_PASS_VIEW]: { group: "Operations", name: "View gate passes" },
  [PERMISSIONS.GATE_PASS_CREATE]: { group: "Operations", name: "Record inward gate pass" },
  [PERMISSIONS.RECEIVE_GOODS]: { group: "Operations", name: "Record goods receiving" },
  [PERMISSIONS.SERVICE_ACCEPT]: { group: "Operations", name: "Record service acceptance" },
  [PERMISSIONS.SERVICE_ACCEPT_ANY]: { group: "Operations", name: "Confirm any service acceptance" },
  [PERMISSIONS.RECEIVING_VIEW]: { group: "Operations", name: "View deliveries" },
  [PERMISSIONS.INSPECTION_VIEW]: { group: "Operations", name: "View inspections" },
  [PERMISSIONS.INSPECTION_PERFORM]: { group: "Operations", name: "Perform technical inspection" },
  [PERMISSIONS.INSPECTION_SCHEDULE]: { group: "Operations", name: "Schedule an inspection" },
  [PERMISSIONS.GRN_VIEW]: { group: "Operations", name: "View GRNs" },
  [PERMISSIONS.GRN_CREATE]: { group: "Operations", name: "Create GRN" },
  [PERMISSIONS.GRN_POST]: { group: "Operations", name: "Post GRN to inventory" },
  [PERMISSIONS.GRN_CANCEL]: { group: "Operations", name: "Cancel GRN" },
  [PERMISSIONS.INVENTORY_VIEW]: { group: "Stores", name: "View inventory" },
  [PERMISSIONS.INVENTORY_ADJUST]: { group: "Stores", name: "Adjust inventory" },
  [PERMISSIONS.STORE_ISSUE]: { group: "Stores", name: "Issue stock" },
  [PERMISSIONS.STORE_ISSUE_APPROVE]: { group: "Stores", name: "Approve stock issue" },
  [PERMISSIONS.STORE_TRANSFER]: { group: "Stores", name: "Raise / dispatch store transfer" },
  [PERMISSIONS.STORE_TRANSFER_APPROVE]: { group: "Stores", name: "Approve store transfer" },
  [PERMISSIONS.STACKING_RECORD]: { group: "Stores", name: "Record goods stacking" },
  [PERMISSIONS.INVOICE_VIEW]: { group: "Finance", name: "View invoices" },
  [PERMISSIONS.INVOICE_CREATE]: { group: "Finance", name: "Register vendor invoice" },
  [PERMISSIONS.INVOICE_VERIFY]: { group: "Finance", name: "Run three-way match & verify" },
  [PERMISSIONS.INVOICE_APPROVE]: { group: "Finance", name: "Approve invoice for payment" },
  [PERMISSIONS.INVOICE_EXCEPTION_APPROVE]: { group: "Finance", name: "Approve invoice mismatch exception" },
  [PERMISSIONS.FINANCE_HANDOFF]: { group: "Finance", name: "Hand off to finance" },
  [PERMISSIONS.FINANCE_ACK]: { group: "Finance", name: "Acknowledge finance handoff" },
  [PERMISSIONS.PAYMENT_RECORD]: { group: "Finance", name: "Record payment" },
  [PERMISSIONS.VENDOR_VIEW]: { group: "Vendors", name: "View vendors" },
  [PERMISSIONS.VENDOR_CREATE]: { group: "Vendors", name: "Create vendor" },
  [PERMISSIONS.VENDOR_EDIT]: { group: "Vendors", name: "Edit vendor" },
  [PERMISSIONS.VENDOR_EVALUATE]: { group: "Vendors", name: "Score vendor pre-qualification" },
  [PERMISSIONS.VENDOR_APPROVE]: { group: "Vendors", name: "Approve vendor" },
  [PERMISSIONS.VENDOR_ISSUE_RAISE]: { group: "Vendors", name: "Raise vendor issue" },
  [PERMISSIONS.VENDOR_BLACKLIST]: { group: "Vendors", name: "Decide blacklisting" },
  [PERMISSIONS.VENDOR_AUDIT_REVIEW]: { group: "Vendors", name: "Audit review of vendor case" },
  [PERMISSIONS.VENDOR_FINANCIALS_VIEW]: { group: "Vendors", name: "View vendor banking details" },
  [PERMISSIONS.ASSET_VIEW]: { group: "Assets", name: "View asset register" },
  [PERMISSIONS.ASSET_MANAGE]: { group: "Assets", name: "Tag & manage assets" },
  [PERMISSIONS.DISPOSAL_VIEW]: { group: "Assets", name: "View disposal cases" },
  [PERMISSIONS.DISPOSAL_CREATE]: { group: "Assets", name: "Raise disposal case" },
  [PERMISSIONS.DISPOSAL_APPROVE]: { group: "Assets", name: "Approve disposal" },
  [PERMISSIONS.DISPOSAL_AUDIT_REVIEW]: { group: "Assets", name: "Audit review of disposal" },
  [PERMISSIONS.DISPOSAL_MANAGEMENT_APPROVE]: { group: "Assets", name: "Management approval of disposal" },
  [PERMISSIONS.ANALYTICS_VIEW]: { group: "Analytics", name: "View analytics" },
  [PERMISSIONS.ANALYTICS_VIEW_ALL_ENTITIES]: { group: "Analytics", name: "View analytics across all entities" },
  [PERMISSIONS.EXPORT_DATA]: { group: "Analytics", name: "Export data" },
  [PERMISSIONS.AUDIT_VIEW]: { group: "Governance", name: "View audit trail" },
  [PERMISSIONS.DOCUMENT_VIEW]: { group: "Documents", name: "View documents" },
  [PERMISSIONS.DOCUMENT_UPLOAD]: { group: "Documents", name: "Upload documents" },
  [PERMISSIONS.DOCUMENT_VIEW_CONFIDENTIAL]: { group: "Documents", name: "View confidential documents" },
  [PERMISSIONS.DOCUMENT_VIEW_RESTRICTED]: { group: "Documents", name: "View restricted documents" },
  [PERMISSIONS.DOCUMENT_DELETE]: { group: "Documents", name: "Archive documents" },
  [PERMISSIONS.EXCEPTION_VIEW]: { group: "Governance", name: "View exceptions" },
  [PERMISSIONS.EXCEPTION_MANAGE]: { group: "Governance", name: "Resolve exceptions" },
  [PERMISSIONS.CONFIG_MANAGE]: { group: "Administration", name: "Manage configuration" },
  [PERMISSIONS.USER_MANAGE]: { group: "Administration", name: "Manage users" },
  [PERMISSIONS.ROLE_MANAGE]: { group: "Administration", name: "Manage roles & permissions" },
  [PERMISSIONS.MASTER_DATA_MANAGE]: { group: "Administration", name: "Manage master data" },
  [PERMISSIONS.APPROVAL_RULE_MANAGE]: { group: "Administration", name: "Manage approval rules" },
};

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const P = PERMISSIONS;

const REQUESTER_BASE = [
  P.REQUIREMENT_VIEW,
  P.REQUIREMENT_CREATE,
  P.REQUIREMENT_EDIT,
  P.REQUIREMENT_SUBMIT,
  P.SR_VIEW,
  P.SR_CREATE,
  P.PR_VIEW,
  P.PR_CREATE,
  P.PR_EDIT,
  P.PR_SUBMIT,
  P.DOCUMENT_VIEW,
  P.DOCUMENT_UPLOAD,
  P.PETTY_CASH_VIEW,
  P.PETTY_CASH_CREATE,
  P.INVENTORY_VIEW,
  P.STORE_ISSUE,
  P.SERVICE_ACCEPT,
];

const PROCUREMENT_CORE = [
  P.BUDGET_VIEW,
  P.VARIANCE_VIEW,
  P.RETURN_VIEW,
  P.RETURN_AUTHORISE,
  P.MASTER_VIEW,
  P.TAX_VIEW,
  P.REQUIREMENT_VIEW,
  P.REQUIREMENT_VIEW_ALL,
  P.REQUIREMENT_CHECK_STOCK,
  P.REQUIREMENT_DECIDE,
  P.SR_VIEW,
  P.PR_VIEW,
  P.PR_VIEW_ALL,
  P.PR_HOLD,
  P.PR_RETURN,
  P.PR_CLARIFY,
  P.RFQ_VIEW,
  P.RFQ_ISSUE,
  P.QUOTE_VIEW,
  P.QUOTE_ENTER,
  P.COMPARATIVE_VIEW,
  P.COMPARATIVE_CREATE,
  P.NEGOTIATE,
  P.VENDOR_SELECT,
  P.PO_VIEW,
  P.PO_CREATE,
  P.PO_EDIT,
  P.VENDOR_VIEW,
  P.VENDOR_CREATE,
  P.VENDOR_EDIT,
  P.VENDOR_EVALUATE,
  P.VENDOR_ISSUE_RAISE,
  P.DOCUMENT_VIEW,
  P.DOCUMENT_UPLOAD,
  P.DOCUMENT_VIEW_CONFIDENTIAL,
  P.GRN_VIEW,
  P.INVENTORY_VIEW,
  P.RECEIVING_VIEW,
  P.INSPECTION_VIEW,
  P.INSPECTION_SCHEDULE,
  P.SERVICE_ACCEPT,
  P.CPC_CASE_RAISE,
  P.INVOICE_VIEW,
  P.INVOICE_CREATE,
  P.INVOICE_VERIFY,
  P.ANALYTICS_VIEW,
  P.EXPORT_DATA,
  P.EXCEPTION_VIEW,
  P.EXCEPTION_MANAGE,
  P.CPC_VIEW,
  P.PETTY_CASH_VIEW,
  P.PETTY_CASH_EVALUATE,
  P.GATE_PASS_VIEW,
  P.ASSET_VIEW,
  P.DISPOSAL_VIEW,
];

/**
 * Role → permission grants. Roles are additive; a user with several roles gets
 * the union.
 */
export const ROLE_DEFINITIONS: Array<{
  code: string;
  name: string;
  description: string;
  rank: number;
  permissions: string[];
}> = [
  {
    code: "REQUESTER",
    name: "Requester",
    description: "Raises purchase requisitions and petty cash requests for their department.",
    rank: 10,
    permissions: REQUESTER_BASE,
  },
  {
    code: "HOD",
    name: "Department Head / HOD",
    description: "Approves departmental requisitions and sits on CPC for their department's cases.",
    rank: 40,
    permissions: [
      ...REQUESTER_BASE,
      // A department head is handed a sheet of their department's
      // responsibilities at the kickoff meeting, so they can see the project
      // and update their own lines — but not run it.
      P.BUILD_OUT_VIEW,
      P.BUILD_OUT_TASK_UPDATE,
      P.RNC_VIEW,
      P.PR_VIEW_ALL,
      P.PR_APPROVE,
      P.PR_REJECT,
      P.PR_RETURN,
      P.PR_CLARIFY,
      P.PR_HOLD,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.PO_VIEW,
      P.VENDOR_VIEW,
      P.ANALYTICS_VIEW,
      P.STORE_ISSUE_APPROVE,
      P.REQUIREMENT_VIEW_ALL,
      P.REQUIREMENT_DECIDE,
      P.SR_APPROVE,
      P.SR_APPROVE_HOD,
      P.EXCEPTION_VIEW,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
      P.ASSET_VIEW,
    ],
  },
  {
    code: "PROCUREMENT_OFFICER",
    name: "Procurement Officer",
    description: "Runs day-to-day sourcing: RFQs, quotations, comparatives, POs.",
    rank: 35,
    permissions: [...PROCUREMENT_CORE, P.PR_CREATE, P.PR_EDIT, P.PR_SUBMIT],
  },
  {
    code: "BUYER",
    name: "Buyer",
    description: "Category buyer executing sourcing and negotiation.",
    rank: 30,
    permissions: PROCUREMENT_CORE,
  },
  {
    code: "PROCUREMENT_SENIOR_MANAGER",
    name: "Procurement Senior Manager",
    description: "Reviews sourcing decisions, approves POs and invoices within threshold.",
    rank: 60,
    permissions: [
      ...PROCUREMENT_CORE,
      P.PR_APPROVE,
      P.PO_APPROVE,
      P.PO_ISSUE,
      P.PO_CLOSE,
      P.COMPARATIVE_VERIFY,
      P.INVOICE_APPROVE,
      P.VENDOR_APPROVE,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_MANAGE,
      P.PETTY_CASH_APPROVE,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.AUDIT_VIEW,
      P.DISPOSAL_APPROVE,
      P.STORE_TRANSFER_APPROVE,
      P.WORK_ORDER_VIEW,
      P.WORK_ORDER_APPROVE,
    ],
  },
  {
    code: "PROCUREMENT_DIRECTOR",
    name: "Procurement Director",
    description: "Owns the procurement function; CPC member; final procurement authority.",
    rank: 80,
    permissions: [
      ...PROCUREMENT_CORE,
      // image22 seats the Director Procurement on every regional rental
      // committee as a permanent-mandatory member.
      P.BUILD_OUT_VIEW,
      P.RNC_VIEW,
      P.RNC_DECIDE,
      P.PR_APPROVE,
      P.PR_REJECT,
      P.PO_APPROVE,
      P.PO_ISSUE,
      P.PO_CLOSE,
      P.PO_CANCEL,
      P.COMPARATIVE_VERIFY,
      P.INVOICE_APPROVE,
      P.INVOICE_EXCEPTION_APPROVE,
      P.FINANCE_HANDOFF,
      P.VENDOR_APPROVE,
      P.VENDOR_BLACKLIST,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_DECIDE,
      P.CPC_MANAGE,
      P.PETTY_CASH_APPROVE,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.AUDIT_VIEW,
      P.DISPOSAL_APPROVE,
      P.DISPOSAL_MANAGEMENT_APPROVE,
      P.STORE_TRANSFER_APPROVE,
      P.CONFIG_MANAGE,
      P.APPROVAL_RULE_MANAGE,
      P.DOCUMENT_VIEW_RESTRICTED,
      P.WORK_ORDER_VIEW,
      P.WORK_ORDER_APPROVE,
    ],
  },
  {
    code: "FINANCE_USER",
    name: "Finance User",
    description: "Processes payment handoffs and reconciles petty cash.",
    rank: 35,
    permissions: [
      P.INVOICE_VIEW,
      P.INVOICE_CREATE,
      P.INVOICE_VERIFY,
      P.FINANCE_ACK,
      P.PAYMENT_RECORD,
      P.PO_VIEW,
      P.GRN_VIEW,
      P.VENDOR_VIEW,
      P.VENDOR_FINANCIALS_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.ANALYTICS_VIEW,
      P.EXPORT_DATA,
      P.PETTY_CASH_VIEW,
      P.PETTY_CASH_RECONCILE,
      P.EXCEPTION_VIEW,
      P.INVENTORY_VIEW,
      P.ASSET_VIEW,
      P.VOUCHER_VIEW,
      P.VOUCHER_GENERATE,
      P.VOUCHER_SIGN,
      P.TAX_VIEW,
      P.TAX_VERIFY,
      P.BUDGET_VIEW,
      P.VARIANCE_VIEW,
      P.RETURN_VIEW,
      P.MASTER_VIEW,
    ],
  },
  {
    code: "FINANCE_APPROVER",
    name: "Finance Approver",
    description: "Approves payments and represents finance on CPC.",
    rank: 70,
    permissions: [
      P.INVOICE_VIEW,
      P.INVOICE_VERIFY,
      P.INVOICE_APPROVE,
      P.INVOICE_EXCEPTION_APPROVE,
      P.FINANCE_ACK,
      P.PAYMENT_RECORD,
      P.PO_VIEW,
      P.PO_APPROVE,
      P.GRN_VIEW,
      P.VENDOR_VIEW,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.EXPORT_DATA,
      P.PETTY_CASH_VIEW,
      P.PETTY_CASH_APPROVE,
      P.PETTY_CASH_RECONCILE,
      P.EXCEPTION_VIEW,
      P.AUDIT_VIEW,
      P.VOUCHER_VIEW,
      P.VOUCHER_GENERATE,
      P.VOUCHER_SIGN,
      P.TAX_VIEW,
      P.TAX_MANAGE,
      P.TAX_VERIFY,
      P.BUDGET_VIEW,
      P.BUDGET_MANAGE,
      P.VARIANCE_VIEW,
      P.VARIANCE_RESOLVE,
      P.RETURN_VIEW,
      P.RETURN_AUTHORISE,
      P.MASTER_VIEW,
      P.DISPOSAL_VIEW,
      P.DISPOSAL_APPROVE,
    ],
  },
  {
    code: "CPC_MEMBER",
    name: "CPC Member",
    description: "Central Procurement Committee member with voting rights.",
    rank: 65,
    permissions: [
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.PR_VIEW_ALL,
      P.PR_VIEW,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.RFQ_VIEW,
      P.PO_VIEW,
      P.VENDOR_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.ANALYTICS_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "TECHNICAL_INSPECTOR",
    name: "Technical Inspector",
    description: "Performs technical inspection of received goods.",
    rank: 30,
    permissions: [
      P.INSPECTION_VIEW,
      P.INSPECTION_SCHEDULE,
      P.INSPECTION_PERFORM,
      P.RECEIVING_VIEW,
      P.GRN_VIEW,
      P.PO_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INVENTORY_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "STORE_RECEIVER",
    name: "Store Receiver",
    description: "Physically verifies and receives goods at a store.",
    rank: 20,
    permissions: [
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.STACKING_RECORD,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INSPECTION_VIEW,
      P.INSPECTION_SCHEDULE,
      P.EXCEPTION_VIEW,
      P.SR_VIEW,
      P.SR_ISSUE,
      P.STORE_ISSUE,
      P.VARIANCE_VIEW,
      P.RETURN_VIEW,
      P.RETURN_CREATE,
    ],
  },
  {
    code: "STORE_MANAGER",
    name: "Store Manager",
    description: "Runs a store: receiving, GRN posting, issuance, transfers.",
    rank: 45,
    permissions: [
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.GRN_POST,
      P.GRN_CANCEL,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_ADJUST,
      P.STORE_ISSUE,
      P.STORE_ISSUE_APPROVE,
      P.STORE_TRANSFER,
      P.SR_VIEW,
      P.SR_APPROVE,
      P.SR_APPROVE_CROSS_STORE,
      P.SR_ISSUE,
      P.INVENTORY_RESERVE,
      P.VARIANCE_VIEW,
      P.VARIANCE_RESOLVE,
      P.RETURN_VIEW,
      P.RETURN_CREATE,
      P.ASSET_INSURANCE_MANAGE,
      P.MASTER_VIEW,
      P.REQUIREMENT_VIEW_ALL,
      P.REQUIREMENT_CHECK_STOCK,
      P.STACKING_RECORD,
      P.ASSET_VIEW,
      P.ASSET_MANAGE,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INSPECTION_VIEW,
      P.INSPECTION_SCHEDULE,
      P.EXCEPTION_VIEW,
      P.EXCEPTION_MANAGE,
      P.ANALYTICS_VIEW,
      P.EXPORT_DATA,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
    ],
  },
  {
    code: "WAREHOUSE_MANAGER",
    name: "Warehouse Manager",
    description: "Central warehouse owner with transfer approval authority.",
    rank: 50,
    permissions: [
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.GRN_POST,
      P.GRN_CANCEL,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_ADJUST,
      P.STORE_ISSUE,
      P.STORE_ISSUE_APPROVE,
      P.STORE_TRANSFER,
      P.STORE_TRANSFER_APPROVE,
      P.STACKING_RECORD,
      P.ASSET_VIEW,
      P.ASSET_MANAGE,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INSPECTION_VIEW,
      P.INSPECTION_SCHEDULE,
      P.EXCEPTION_VIEW,
      P.EXCEPTION_MANAGE,
      P.ANALYTICS_VIEW,
      P.EXPORT_DATA,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
    ],
  },
  {
    code: "SITE_STORE_USER",
    name: "Site Store User",
    description: "Receives project material at a site store.",
    rank: 20,
    permissions: [
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.GRN_POST,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.STORE_ISSUE,
      P.STACKING_RECORD,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INSPECTION_VIEW,
      P.INSPECTION_SCHEDULE,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "ADMIN_FLOOR_MANAGER",
    name: "Admin / Floor Manager",
    description:
      "Office administration, gate passes, office store and petty cash — and build-outs, which the Checklist of Roles & Responsibilities gives Administration more lines on than any other department.",
    rank: 35,
    permissions: [
      ...REQUESTER_BASE,
      // Build-outs. Administration gathers requirements, runs the day-wise
      // vendor schedule and monitors the BOQ against actual, so it owns the
      // project — but not the go-ahead, which is management's.
      P.BUILD_OUT_VIEW,
      P.BUILD_OUT_CREATE,
      P.BUILD_OUT_EDIT,
      P.BUILD_OUT_TASK_UPDATE,
      P.BUILD_OUT_MEETING_MANAGE,
      P.BUILD_OUT_CLOSE,
      // RN-003 puts the arranging of an RNC with the HOD Sales or Admin.
      P.RNC_VIEW,
      P.RNC_CASE_RAISE,
      P.RNC_MANAGE,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GRN_VIEW,
      P.INSPECTION_SCHEDULE,
      P.GRN_CREATE,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.STORE_ISSUE,
      P.ASSET_VIEW,
      P.ASSET_MANAGE,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
      P.EXCEPTION_VIEW,
      // §4.6: the work order is raised and issued by admin, on procurement's
      // negotiated rates. Deliberately no audit-review permission here — the
      // department that raises the order cannot be the one that clears it.
      P.WORK_ORDER_VIEW,
      P.WORK_ORDER_CREATE,
      P.WORK_ORDER_EDIT,
      P.WORK_ORDER_ISSUE,
      P.WORK_ORDER_CLOSE,
    ],
  },
  {
    code: "SECURITY",
    name: "Security",
    description: "Records vehicle arrival and inward gate passes at the gate.",
    rank: 10,
    permissions: [P.GATE_PASS_VIEW, P.GATE_PASS_CREATE, P.PO_VIEW, P.DOCUMENT_UPLOAD, P.DOCUMENT_VIEW],
  },
  {
    code: "AUDIT_USER",
    name: "Audit User",
    description: "Read-only across the system plus audit review of vendor and disposal cases.",
    rank: 55,
    permissions: [
      P.BUILD_OUT_VIEW,
      P.RNC_VIEW,
      P.PR_VIEW,
      P.PR_VIEW_ALL,
      P.RFQ_VIEW,
      P.QUOTE_VIEW,
      P.COMPARATIVE_VIEW,
      P.PO_VIEW,
      P.GRN_VIEW,
      P.RECEIVING_VIEW,
      P.INSPECTION_VIEW,
      P.GATE_PASS_VIEW,
      P.INVOICE_VIEW,
      P.INVENTORY_VIEW,
      P.ASSET_VIEW,
      P.DISPOSAL_VIEW,
      P.DISPOSAL_AUDIT_REVIEW,
      P.VENDOR_VIEW,
      P.VENDOR_AUDIT_REVIEW,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_VIEW,
      P.AUDIT_VIEW,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.EXPORT_DATA,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.DOCUMENT_VIEW_RESTRICTED,
      P.EXCEPTION_VIEW,
      P.PETTY_CASH_VIEW,
      // The CPC ToR puts the review of an admin work order outside CPC's domain
      // with Internal Audit, before the order is finalised. This is the only
      // role that holds it, and it deliberately cannot raise or issue one.
      P.WORK_ORDER_VIEW,
      P.WORK_ORDER_AUDIT_REVIEW,
    ],
  },
  {
    code: "PM_USER",
    name: "PM User",
    description: "Project manager raising and validating ZD Material Demands.",
    rank: 40,
    permissions: [
      ...REQUESTER_BASE,
      P.PR_VIEW_ALL,
      P.PR_APPROVE,
      P.PR_RETURN,
      P.PR_CLARIFY,
      P.RFQ_VIEW,
      P.QUOTE_VIEW,
      P.COMPARATIVE_VIEW,
      P.PO_VIEW,
      P.GRN_VIEW,
      P.RECEIVING_VIEW,
      P.INSPECTION_VIEW,
      P.INSPECTION_PERFORM,
      P.VENDOR_VIEW,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.ANALYTICS_VIEW,
      P.EXCEPTION_VIEW,
      P.ASSET_VIEW,
    ],
  },
  {
    code: "DESIGN_USER",
    name: "Design User",
    description: "Design team validating specifications, BOQs and drawings.",
    rank: 25,
    permissions: [
      ...REQUESTER_BASE,
      P.PR_VIEW_ALL,
      P.PR_CLARIFY,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.INSPECTION_VIEW,
      P.INSPECTION_PERFORM,
      P.VENDOR_VIEW,
    ],
  },
  {
    code: "IT_USER",
    name: "IT User",
    description: "IT department: specifies and inspects IT equipment.",
    rank: 30,
    permissions: [
      ...REQUESTER_BASE,
      P.PR_VIEW_ALL,
      P.INSPECTION_VIEW,
      P.INSPECTION_PERFORM,
      P.ASSET_VIEW,
      P.ASSET_MANAGE,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.PO_VIEW,
      P.VENDOR_VIEW,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "MANAGEMENT_COMMITTEE",
    name: "Management Committee Member",
    description: "Executive oversight, disposal sign-off and portfolio analytics.",
    rank: 90,
    permissions: [
      P.PR_VIEW,
      P.PR_VIEW_ALL,
      P.PO_VIEW,
      P.RFQ_VIEW,
      P.QUOTE_VIEW,
      P.COMPARATIVE_VIEW,
      P.GRN_VIEW,
      P.INVOICE_VIEW,
      P.INVENTORY_VIEW,
      P.VENDOR_VIEW,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      // BO-002 — the go-ahead is management's own act, and deliberately not
      // held by whoever raises the build-out.
      P.BUILD_OUT_VIEW,
      P.BUILD_OUT_MANAGEMENT_APPROVE,
      P.BUILD_OUT_CLOSE,
      P.RNC_VIEW,
      P.RNC_DECIDE,
      P.ASSET_VIEW,
      P.DISPOSAL_VIEW,
      P.DISPOSAL_MANAGEMENT_APPROVE,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.EXPORT_DATA,
      P.AUDIT_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "CEO_OFFICE",
    name: "Office of the CEO",
    description:
      "PC-023's second approval above the value tier. Ships with nobody in it: who constitutes the Office of the CEO is a decision for the business, and seeding a plausible name would be inventing an approver. The access review lists roles nobody holds, so the gap is visible rather than silent, and the enforcement flag stays off until somebody is named.",
    rank: 95,
    permissions: [
      P.PR_VIEW,
      P.PR_VIEW_ALL,
      P.PO_VIEW,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.VENDOR_VIEW,
      P.CPC_VIEW,
      // The one permission that is the point of this role, and which no
      // committee role holds.
      P.CPC_CEO_APPROVE,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.DOCUMENT_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "SYSTEM_ADMIN",
    name: "System Administrator",
    description: "Full system access including configuration and RBAC.",
    rank: 100,
    permissions: ALL_PERMISSIONS as unknown as string[],
  },
];

export function permissionsForRoles(roleCodes: string[]): Set<string> {
  const out = new Set<string>();
  for (const rc of roleCodes) {
    const def = ROLE_DEFINITIONS.find((r) => r.code === rc);
    if (def) def.permissions.forEach((p) => out.add(p));
  }
  return out;
}
