/**
 * Permission catalogue and role → permission mapping.
 * Every server action / route handler resolves against these codes; the UI only
 * mirrors them for affordance, it is never the enforcement point.
 */

export const PERMISSIONS = {
  // Requirements — the demand front door
  REQUIREMENT_VIEW: "requirements.view",
  REQUIREMENT_VIEW_ALL: "requirements.view_all",
  REQUIREMENT_CREATE: "requirements.create",
  REQUIREMENT_EDIT: "requirements.edit",
  REQUIREMENT_SUBMIT: "requirements.submit",
  REQUIREMENT_CHECK_STOCK: "requirements.check_stock",
  REQUIREMENT_DECIDE: "requirements.decide",
  REQUIREMENT_CANCEL: "requirements.cancel",

  // Store requisitions
  SR_VIEW: "store_requisition.view",
  SR_CREATE: "store_requisition.create",
  SR_APPROVE: "store_requisition.approve",
  SR_APPROVE_HOD: "store_requisition.approve_hod",
  SR_APPROVE_CROSS_STORE: "store_requisition.approve_cross_store",
  SR_ISSUE: "store_requisition.issue",
  INVENTORY_RESERVE: "inventory.reserve",

  // Requisitions
  PR_VIEW: "pr.view",
  PR_VIEW_ALL: "pr.view_all",
  PR_CREATE: "pr.create",
  PR_EDIT: "pr.edit",
  PR_SUBMIT: "pr.submit",
  PR_APPROVE: "pr.approve",
  PR_REJECT: "pr.reject",
  PR_RETURN: "pr.return",
  PR_CANCEL: "pr.cancel",
  PR_HOLD: "pr.hold",
  PR_CLARIFY: "pr.clarify",

  // Sourcing
  RFQ_VIEW: "rfq.view",
  RFQ_ISSUE: "rfq.issue",
  QUOTE_ENTER: "quote.enter",
  QUOTE_VIEW: "quote.view",
  COMPARATIVE_CREATE: "comparative.create",
  COMPARATIVE_VIEW: "comparative.view",
  NEGOTIATE: "negotiate.record",
  VENDOR_SELECT: "sourcing.select_vendor",

  // CPC
  CPC_VIEW: "cpc.view",
  CPC_DECIDE: "cpc.decide",
  CPC_MANAGE: "cpc.manage",

  // Purchase orders
  PO_VIEW: "po.view",
  PO_CREATE: "po.create",
  PO_EDIT: "po.edit",
  PO_APPROVE: "po.approve",
  PO_ISSUE: "po.issue",
  PO_CLOSE: "po.close",
  PO_CANCEL: "po.cancel",

  // Petty cash
  PETTY_CASH_VIEW: "petty_cash.view",
  PETTY_CASH_CREATE: "petty_cash.create",
  PETTY_CASH_EVALUATE: "petty_cash.evaluate",
  PETTY_CASH_APPROVE: "petty_cash.approve",
  PETTY_CASH_RECONCILE: "petty_cash.reconcile",

  // Operations
  GATE_PASS_VIEW: "gate_pass.view",
  GATE_PASS_CREATE: "gate_pass.create",
  RECEIVE_GOODS: "receiving.record",
  RECEIVING_VIEW: "receiving.view",
  INSPECTION_VIEW: "inspection.view",
  INSPECTION_PERFORM: "inspection.perform",
  GRN_VIEW: "grn.view",
  GRN_CREATE: "grn.create",
  GRN_POST: "grn.post",
  GRN_CANCEL: "grn.cancel",

  // Stores & inventory
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_ADJUST: "inventory.adjust",
  STORE_ISSUE: "store.issue",
  STORE_ISSUE_APPROVE: "store.issue_approve",
  STORE_TRANSFER: "store.transfer",
  STORE_TRANSFER_APPROVE: "store.transfer_approve",
  STACKING_RECORD: "store.stacking",

  // Invoices & finance
  INVOICE_VIEW: "invoice.view",
  INVOICE_CREATE: "invoice.create",
  INVOICE_VERIFY: "invoice.verify",
  INVOICE_APPROVE: "invoice.approve",
  INVOICE_EXCEPTION_APPROVE: "invoice.exception_approve",
  FINANCE_HANDOFF: "finance.handoff",
  FINANCE_ACK: "finance.acknowledge",
  PAYMENT_RECORD: "finance.record_payment",

  // Vendors
  VENDOR_VIEW: "vendor.view",
  VENDOR_CREATE: "vendor.create",
  VENDOR_EDIT: "vendor.edit",
  VENDOR_EVALUATE: "vendor.evaluate",
  VENDOR_APPROVE: "vendor.approve",
  VENDOR_ISSUE_RAISE: "vendor.issue_raise",
  VENDOR_BLACKLIST: "vendor.blacklist",
  VENDOR_AUDIT_REVIEW: "vendor.audit_review",
  VENDOR_FINANCIALS_VIEW: "vendor.view_financials",

  // Assets & disposal
  ASSET_VIEW: "asset.view",
  ASSET_MANAGE: "asset.manage",
  DISPOSAL_VIEW: "disposal.view",
  DISPOSAL_CREATE: "disposal.create",
  DISPOSAL_APPROVE: "disposal.approve",
  DISPOSAL_AUDIT_REVIEW: "disposal.audit_review",
  DISPOSAL_MANAGEMENT_APPROVE: "disposal.management_approve",

  // Cross-cutting
  ANALYTICS_VIEW: "analytics.view",
  ANALYTICS_VIEW_ALL_ENTITIES: "analytics.view_all_entities",
  EXPORT_DATA: "data.export",
  AUDIT_VIEW: "audit.view",
  DOCUMENT_VIEW: "document.view",
  DOCUMENT_UPLOAD: "document.upload",
  DOCUMENT_VIEW_CONFIDENTIAL: "document.view_confidential",
  DOCUMENT_VIEW_RESTRICTED: "document.view_restricted",
  DOCUMENT_DELETE: "document.delete",
  EXCEPTION_VIEW: "exception.view",
  EXCEPTION_MANAGE: "exception.manage",

  // Administration
  CONFIG_MANAGE: "admin.config",
  USER_MANAGE: "admin.users",
  ROLE_MANAGE: "admin.roles",
  MASTER_DATA_MANAGE: "admin.master_data",
  APPROVAL_RULE_MANAGE: "admin.approval_rules",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

type PermMeta = { group: string; name: string };

export const PERMISSION_META: Record<string, PermMeta> = {
  [PERMISSIONS.REQUIREMENT_VIEW]: { group: "Requirements", name: "View own/department requirements" },
  [PERMISSIONS.REQUIREMENT_VIEW_ALL]: { group: "Requirements", name: "View all requirements" },
  [PERMISSIONS.REQUIREMENT_CREATE]: { group: "Requirements", name: "Raise a requirement" },
  [PERMISSIONS.REQUIREMENT_EDIT]: { group: "Requirements", name: "Edit a requirement" },
  [PERMISSIONS.REQUIREMENT_SUBMIT]: { group: "Requirements", name: "Submit a requirement" },
  [PERMISSIONS.REQUIREMENT_CHECK_STOCK]: { group: "Requirements", name: "Run the availability check" },
  [PERMISSIONS.REQUIREMENT_DECIDE]: { group: "Requirements", name: "Decide stock or procurement" },
  [PERMISSIONS.REQUIREMENT_CANCEL]: { group: "Requirements", name: "Cancel a requirement" },
  [PERMISSIONS.SR_VIEW]: { group: "Store requisitions", name: "View store requisitions" },
  [PERMISSIONS.SR_CREATE]: { group: "Store requisitions", name: "Raise a store requisition" },
  [PERMISSIONS.SR_APPROVE]: { group: "Store requisitions", name: "Approve a store requisition" },
  [PERMISSIONS.SR_APPROVE_HOD]: { group: "Store requisitions", name: "Approve as department head" },
  [PERMISSIONS.SR_APPROVE_CROSS_STORE]: { group: "Store requisitions", name: "Authorise cross-store fulfilment" },
  [PERMISSIONS.SR_ISSUE]: { group: "Store requisitions", name: "Issue against a store requisition" },
  [PERMISSIONS.INVENTORY_RESERVE]: { group: "Stores", name: "Reserve and release stock" },
  [PERMISSIONS.PR_VIEW]: { group: "Requisitions", name: "View own/department requisitions" },
  [PERMISSIONS.PR_VIEW_ALL]: { group: "Requisitions", name: "View all requisitions" },
  [PERMISSIONS.PR_CREATE]: { group: "Requisitions", name: "Create requisition" },
  [PERMISSIONS.PR_EDIT]: { group: "Requisitions", name: "Edit requisition" },
  [PERMISSIONS.PR_SUBMIT]: { group: "Requisitions", name: "Submit requisition" },
  [PERMISSIONS.PR_APPROVE]: { group: "Requisitions", name: "Approve requisition" },
  [PERMISSIONS.PR_REJECT]: { group: "Requisitions", name: "Reject requisition" },
  [PERMISSIONS.PR_RETURN]: { group: "Requisitions", name: "Return requisition" },
  [PERMISSIONS.PR_CANCEL]: { group: "Requisitions", name: "Cancel requisition" },
  [PERMISSIONS.PR_HOLD]: { group: "Requisitions", name: "Place requisition on hold" },
  [PERMISSIONS.PR_CLARIFY]: { group: "Requisitions", name: "Request clarification" },
  [PERMISSIONS.RFQ_VIEW]: { group: "Sourcing", name: "View RFQs" },
  [PERMISSIONS.RFQ_ISSUE]: { group: "Sourcing", name: "Create & issue RFQ" },
  [PERMISSIONS.QUOTE_ENTER]: { group: "Sourcing", name: "Enter vendor quotations" },
  [PERMISSIONS.QUOTE_VIEW]: { group: "Sourcing", name: "View quotations" },
  [PERMISSIONS.COMPARATIVE_CREATE]: { group: "Sourcing", name: "Build comparative analysis" },
  [PERMISSIONS.COMPARATIVE_VIEW]: { group: "Sourcing", name: "View comparatives" },
  [PERMISSIONS.NEGOTIATE]: { group: "Sourcing", name: "Record negotiation rounds" },
  [PERMISSIONS.VENDOR_SELECT]: { group: "Sourcing", name: "Select awarded vendor" },
  [PERMISSIONS.CPC_VIEW]: { group: "CPC", name: "View CPC cases" },
  [PERMISSIONS.CPC_DECIDE]: { group: "CPC", name: "Cast CPC decision" },
  [PERMISSIONS.CPC_MANAGE]: { group: "CPC", name: "Manage CPC meetings & agenda" },
  [PERMISSIONS.PO_VIEW]: { group: "Purchase Orders", name: "View purchase orders" },
  [PERMISSIONS.PO_CREATE]: { group: "Purchase Orders", name: "Create purchase order" },
  [PERMISSIONS.PO_EDIT]: { group: "Purchase Orders", name: "Edit purchase order" },
  [PERMISSIONS.PO_APPROVE]: { group: "Purchase Orders", name: "Approve purchase order" },
  [PERMISSIONS.PO_ISSUE]: { group: "Purchase Orders", name: "Issue purchase order to vendor" },
  [PERMISSIONS.PO_CLOSE]: { group: "Purchase Orders", name: "Close purchase order" },
  [PERMISSIONS.PO_CANCEL]: { group: "Purchase Orders", name: "Cancel purchase order" },
  [PERMISSIONS.PETTY_CASH_VIEW]: { group: "Petty Cash", name: "View petty cash requests" },
  [PERMISSIONS.PETTY_CASH_CREATE]: { group: "Petty Cash", name: "Raise petty cash request" },
  [PERMISSIONS.PETTY_CASH_EVALUATE]: { group: "Petty Cash", name: "Evaluate & record market quotes" },
  [PERMISSIONS.PETTY_CASH_APPROVE]: { group: "Petty Cash", name: "Approve cash purchase / voucher" },
  [PERMISSIONS.PETTY_CASH_RECONCILE]: { group: "Petty Cash", name: "Reconcile petty cash" },
  [PERMISSIONS.GATE_PASS_VIEW]: { group: "Operations", name: "View gate passes" },
  [PERMISSIONS.GATE_PASS_CREATE]: { group: "Operations", name: "Record inward gate pass" },
  [PERMISSIONS.RECEIVE_GOODS]: { group: "Operations", name: "Record goods receiving" },
  [PERMISSIONS.RECEIVING_VIEW]: { group: "Operations", name: "View deliveries" },
  [PERMISSIONS.INSPECTION_VIEW]: { group: "Operations", name: "View inspections" },
  [PERMISSIONS.INSPECTION_PERFORM]: { group: "Operations", name: "Perform technical inspection" },
  [PERMISSIONS.GRN_VIEW]: { group: "Operations", name: "View GRNs" },
  [PERMISSIONS.GRN_CREATE]: { group: "Operations", name: "Create GRN" },
  [PERMISSIONS.GRN_POST]: { group: "Operations", name: "Post GRN to inventory" },
  [PERMISSIONS.GRN_CANCEL]: { group: "Operations", name: "Cancel GRN" },
  [PERMISSIONS.INVENTORY_VIEW]: { group: "Stores", name: "View inventory" },
  [PERMISSIONS.INVENTORY_ADJUST]: { group: "Stores", name: "Adjust inventory" },
  [PERMISSIONS.STORE_ISSUE]: { group: "Stores", name: "Issue stock" },
  [PERMISSIONS.STORE_ISSUE_APPROVE]: { group: "Stores", name: "Approve stock issue" },
  [PERMISSIONS.STORE_TRANSFER]: { group: "Stores", name: "Raise / dispatch store transfer" },
  [PERMISSIONS.STORE_TRANSFER_APPROVE]: { group: "Stores", name: "Approve store transfer" },
  [PERMISSIONS.STACKING_RECORD]: { group: "Stores", name: "Record goods stacking" },
  [PERMISSIONS.INVOICE_VIEW]: { group: "Finance", name: "View invoices" },
  [PERMISSIONS.INVOICE_CREATE]: { group: "Finance", name: "Register vendor invoice" },
  [PERMISSIONS.INVOICE_VERIFY]: { group: "Finance", name: "Run three-way match & verify" },
  [PERMISSIONS.INVOICE_APPROVE]: { group: "Finance", name: "Approve invoice for payment" },
  [PERMISSIONS.INVOICE_EXCEPTION_APPROVE]: { group: "Finance", name: "Approve invoice mismatch exception" },
  [PERMISSIONS.FINANCE_HANDOFF]: { group: "Finance", name: "Hand off to finance" },
  [PERMISSIONS.FINANCE_ACK]: { group: "Finance", name: "Acknowledge finance handoff" },
  [PERMISSIONS.PAYMENT_RECORD]: { group: "Finance", name: "Record payment" },
  [PERMISSIONS.VENDOR_VIEW]: { group: "Vendors", name: "View vendors" },
  [PERMISSIONS.VENDOR_CREATE]: { group: "Vendors", name: "Create vendor" },
  [PERMISSIONS.VENDOR_EDIT]: { group: "Vendors", name: "Edit vendor" },
  [PERMISSIONS.VENDOR_EVALUATE]: { group: "Vendors", name: "Score vendor pre-qualification" },
  [PERMISSIONS.VENDOR_APPROVE]: { group: "Vendors", name: "Approve vendor" },
  [PERMISSIONS.VENDOR_ISSUE_RAISE]: { group: "Vendors", name: "Raise vendor issue" },
  [PERMISSIONS.VENDOR_BLACKLIST]: { group: "Vendors", name: "Decide blacklisting" },
  [PERMISSIONS.VENDOR_AUDIT_REVIEW]: { group: "Vendors", name: "Audit review of vendor case" },
  [PERMISSIONS.VENDOR_FINANCIALS_VIEW]: { group: "Vendors", name: "View vendor banking details" },
  [PERMISSIONS.ASSET_VIEW]: { group: "Assets", name: "View asset register" },
  [PERMISSIONS.ASSET_MANAGE]: { group: "Assets", name: "Tag & manage assets" },
  [PERMISSIONS.DISPOSAL_VIEW]: { group: "Assets", name: "View disposal cases" },
  [PERMISSIONS.DISPOSAL_CREATE]: { group: "Assets", name: "Raise disposal case" },
  [PERMISSIONS.DISPOSAL_APPROVE]: { group: "Assets", name: "Approve disposal" },
  [PERMISSIONS.DISPOSAL_AUDIT_REVIEW]: { group: "Assets", name: "Audit review of disposal" },
  [PERMISSIONS.DISPOSAL_MANAGEMENT_APPROVE]: { group: "Assets", name: "Management approval of disposal" },
  [PERMISSIONS.ANALYTICS_VIEW]: { group: "Analytics", name: "View analytics" },
  [PERMISSIONS.ANALYTICS_VIEW_ALL_ENTITIES]: { group: "Analytics", name: "View analytics across all entities" },
  [PERMISSIONS.EXPORT_DATA]: { group: "Analytics", name: "Export data" },
  [PERMISSIONS.AUDIT_VIEW]: { group: "Governance", name: "View audit trail" },
  [PERMISSIONS.DOCUMENT_VIEW]: { group: "Documents", name: "View documents" },
  [PERMISSIONS.DOCUMENT_UPLOAD]: { group: "Documents", name: "Upload documents" },
  [PERMISSIONS.DOCUMENT_VIEW_CONFIDENTIAL]: { group: "Documents", name: "View confidential documents" },
  [PERMISSIONS.DOCUMENT_VIEW_RESTRICTED]: { group: "Documents", name: "View restricted documents" },
  [PERMISSIONS.DOCUMENT_DELETE]: { group: "Documents", name: "Archive documents" },
  [PERMISSIONS.EXCEPTION_VIEW]: { group: "Governance", name: "View exceptions" },
  [PERMISSIONS.EXCEPTION_MANAGE]: { group: "Governance", name: "Resolve exceptions" },
  [PERMISSIONS.CONFIG_MANAGE]: { group: "Administration", name: "Manage configuration" },
  [PERMISSIONS.USER_MANAGE]: { group: "Administration", name: "Manage users" },
  [PERMISSIONS.ROLE_MANAGE]: { group: "Administration", name: "Manage roles & permissions" },
  [PERMISSIONS.MASTER_DATA_MANAGE]: { group: "Administration", name: "Manage master data" },
  [PERMISSIONS.APPROVAL_RULE_MANAGE]: { group: "Administration", name: "Manage approval rules" },
};

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const P = PERMISSIONS;

const REQUESTER_BASE = [
  P.REQUIREMENT_VIEW,
  P.REQUIREMENT_CREATE,
  P.REQUIREMENT_EDIT,
  P.REQUIREMENT_SUBMIT,
  P.SR_VIEW,
  P.SR_CREATE,
  P.PR_VIEW,
  P.PR_CREATE,
  P.PR_EDIT,
  P.PR_SUBMIT,
  P.DOCUMENT_VIEW,
  P.DOCUMENT_UPLOAD,
  P.PETTY_CASH_VIEW,
  P.PETTY_CASH_CREATE,
  P.INVENTORY_VIEW,
  P.STORE_ISSUE,
];

const PROCUREMENT_CORE = [
  P.REQUIREMENT_VIEW,
  P.REQUIREMENT_VIEW_ALL,
  P.REQUIREMENT_CHECK_STOCK,
  P.REQUIREMENT_DECIDE,
  P.SR_VIEW,
  P.PR_VIEW,
  P.PR_VIEW_ALL,
  P.PR_HOLD,
  P.PR_RETURN,
  P.PR_CLARIFY,
  P.RFQ_VIEW,
  P.RFQ_ISSUE,
  P.QUOTE_VIEW,
  P.QUOTE_ENTER,
  P.COMPARATIVE_VIEW,
  P.COMPARATIVE_CREATE,
  P.NEGOTIATE,
  P.VENDOR_SELECT,
  P.PO_VIEW,
  P.PO_CREATE,
  P.PO_EDIT,
  P.VENDOR_VIEW,
  P.VENDOR_CREATE,
  P.VENDOR_EDIT,
  P.VENDOR_EVALUATE,
  P.VENDOR_ISSUE_RAISE,
  P.DOCUMENT_VIEW,
  P.DOCUMENT_UPLOAD,
  P.DOCUMENT_VIEW_CONFIDENTIAL,
  P.GRN_VIEW,
  P.INVENTORY_VIEW,
  P.RECEIVING_VIEW,
  P.INSPECTION_VIEW,
  P.INVOICE_VIEW,
  P.INVOICE_CREATE,
  P.INVOICE_VERIFY,
  P.ANALYTICS_VIEW,
  P.EXPORT_DATA,
  P.EXCEPTION_VIEW,
  P.EXCEPTION_MANAGE,
  P.CPC_VIEW,
  P.PETTY_CASH_VIEW,
  P.PETTY_CASH_EVALUATE,
  P.GATE_PASS_VIEW,
  P.ASSET_VIEW,
  P.DISPOSAL_VIEW,
];

/**
 * Role → permission grants. Roles are additive; a user with several roles gets
 * the union.
 */
export const ROLE_DEFINITIONS: Array<{
  code: string;
  name: string;
  description: string;
  rank: number;
  permissions: string[];
}> = [
  {
    code: "REQUESTER",
    name: "Requester",
    description: "Raises purchase requisitions and petty cash requests for their department.",
    rank: 10,
    permissions: REQUESTER_BASE,
  },
  {
    code: "HOD",
    name: "Department Head / HOD",
    description: "Approves departmental requisitions and sits on CPC for their department's cases.",
    rank: 40,
    permissions: [
      ...REQUESTER_BASE,
      P.PR_VIEW_ALL,
      P.PR_APPROVE,
      P.PR_REJECT,
      P.PR_RETURN,
      P.PR_CLARIFY,
      P.PR_HOLD,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.PO_VIEW,
      P.VENDOR_VIEW,
      P.ANALYTICS_VIEW,
      P.STORE_ISSUE_APPROVE,
      P.REQUIREMENT_VIEW_ALL,
      P.REQUIREMENT_DECIDE,
      P.SR_APPROVE,
      P.SR_APPROVE_HOD,
      P.EXCEPTION_VIEW,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
      P.ASSET_VIEW,
    ],
  },
  {
    code: "PROCUREMENT_OFFICER",
    name: "Procurement Officer",
    description: "Runs day-to-day sourcing: RFQs, quotations, comparatives, POs.",
    rank: 35,
    permissions: [...PROCUREMENT_CORE, P.PR_CREATE, P.PR_EDIT, P.PR_SUBMIT],
  },
  {
    code: "BUYER",
    name: "Buyer",
    description: "Category buyer executing sourcing and negotiation.",
    rank: 30,
    permissions: PROCUREMENT_CORE,
  },
  {
    code: "PROCUREMENT_SENIOR_MANAGER",
    name: "Procurement Senior Manager",
    description: "Reviews sourcing decisions, approves POs and invoices within threshold.",
    rank: 60,
    permissions: [
      ...PROCUREMENT_CORE,
      P.PR_APPROVE,
      P.PO_APPROVE,
      P.PO_ISSUE,
      P.PO_CLOSE,
      P.INVOICE_APPROVE,
      P.VENDOR_APPROVE,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_MANAGE,
      P.PETTY_CASH_APPROVE,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.AUDIT_VIEW,
      P.DISPOSAL_APPROVE,
      P.STORE_TRANSFER_APPROVE,
    ],
  },
  {
    code: "PROCUREMENT_DIRECTOR",
    name: "Procurement Director",
    description: "Owns the procurement function; CPC member; final procurement authority.",
    rank: 80,
    permissions: [
      ...PROCUREMENT_CORE,
      P.PR_APPROVE,
      P.PR_REJECT,
      P.PO_APPROVE,
      P.PO_ISSUE,
      P.PO_CLOSE,
      P.PO_CANCEL,
      P.INVOICE_APPROVE,
      P.INVOICE_EXCEPTION_APPROVE,
      P.FINANCE_HANDOFF,
      P.VENDOR_APPROVE,
      P.VENDOR_BLACKLIST,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_DECIDE,
      P.CPC_MANAGE,
      P.PETTY_CASH_APPROVE,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.AUDIT_VIEW,
      P.DISPOSAL_APPROVE,
      P.DISPOSAL_MANAGEMENT_APPROVE,
      P.STORE_TRANSFER_APPROVE,
      P.CONFIG_MANAGE,
      P.APPROVAL_RULE_MANAGE,
      P.DOCUMENT_VIEW_RESTRICTED,
    ],
  },
  {
    code: "FINANCE_USER",
    name: "Finance User",
    description: "Processes payment handoffs and reconciles petty cash.",
    rank: 35,
    permissions: [
      P.INVOICE_VIEW,
      P.INVOICE_CREATE,
      P.INVOICE_VERIFY,
      P.FINANCE_ACK,
      P.PAYMENT_RECORD,
      P.PO_VIEW,
      P.GRN_VIEW,
      P.VENDOR_VIEW,
      P.VENDOR_FINANCIALS_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.ANALYTICS_VIEW,
      P.EXPORT_DATA,
      P.PETTY_CASH_VIEW,
      P.PETTY_CASH_RECONCILE,
      P.EXCEPTION_VIEW,
      P.INVENTORY_VIEW,
      P.ASSET_VIEW,
    ],
  },
  {
    code: "FINANCE_APPROVER",
    name: "Finance Approver",
    description: "Approves payments and represents finance on CPC.",
    rank: 70,
    permissions: [
      P.INVOICE_VIEW,
      P.INVOICE_VERIFY,
      P.INVOICE_APPROVE,
      P.INVOICE_EXCEPTION_APPROVE,
      P.FINANCE_ACK,
      P.PAYMENT_RECORD,
      P.PO_VIEW,
      P.PO_APPROVE,
      P.GRN_VIEW,
      P.VENDOR_VIEW,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.EXPORT_DATA,
      P.PETTY_CASH_VIEW,
      P.PETTY_CASH_APPROVE,
      P.PETTY_CASH_RECONCILE,
      P.EXCEPTION_VIEW,
      P.AUDIT_VIEW,
      P.DISPOSAL_VIEW,
      P.DISPOSAL_APPROVE,
    ],
  },
  {
    code: "CPC_MEMBER",
    name: "CPC Member",
    description: "Central Procurement Committee member with voting rights.",
    rank: 65,
    permissions: [
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.PR_VIEW_ALL,
      P.PR_VIEW,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.RFQ_VIEW,
      P.PO_VIEW,
      P.VENDOR_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.ANALYTICS_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "TECHNICAL_INSPECTOR",
    name: "Technical Inspector",
    description: "Performs technical inspection of received goods.",
    rank: 30,
    permissions: [
      P.INSPECTION_VIEW,
      P.INSPECTION_PERFORM,
      P.RECEIVING_VIEW,
      P.GRN_VIEW,
      P.PO_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INVENTORY_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "STORE_RECEIVER",
    name: "Store Receiver",
    description: "Physically verifies and receives goods at a store.",
    rank: 20,
    permissions: [
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.STACKING_RECORD,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INSPECTION_VIEW,
      P.EXCEPTION_VIEW,
      P.SR_VIEW,
      P.SR_ISSUE,
      P.STORE_ISSUE,
    ],
  },
  {
    code: "STORE_MANAGER",
    name: "Store Manager",
    description: "Runs a store: receiving, GRN posting, issuance, transfers.",
    rank: 45,
    permissions: [
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.GRN_POST,
      P.GRN_CANCEL,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_ADJUST,
      P.STORE_ISSUE,
      P.STORE_ISSUE_APPROVE,
      P.STORE_TRANSFER,
      P.SR_VIEW,
      P.SR_APPROVE,
      P.SR_APPROVE_CROSS_STORE,
      P.SR_ISSUE,
      P.INVENTORY_RESERVE,
      P.REQUIREMENT_VIEW_ALL,
      P.REQUIREMENT_CHECK_STOCK,
      P.STACKING_RECORD,
      P.ASSET_VIEW,
      P.ASSET_MANAGE,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INSPECTION_VIEW,
      P.EXCEPTION_VIEW,
      P.EXCEPTION_MANAGE,
      P.ANALYTICS_VIEW,
      P.EXPORT_DATA,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
    ],
  },
  {
    code: "WAREHOUSE_MANAGER",
    name: "Warehouse Manager",
    description: "Central warehouse owner with transfer approval authority.",
    rank: 50,
    permissions: [
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.GRN_POST,
      P.GRN_CANCEL,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_ADJUST,
      P.STORE_ISSUE,
      P.STORE_ISSUE_APPROVE,
      P.STORE_TRANSFER,
      P.STORE_TRANSFER_APPROVE,
      P.STACKING_RECORD,
      P.ASSET_VIEW,
      P.ASSET_MANAGE,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INSPECTION_VIEW,
      P.EXCEPTION_VIEW,
      P.EXCEPTION_MANAGE,
      P.ANALYTICS_VIEW,
      P.EXPORT_DATA,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
    ],
  },
  {
    code: "SITE_STORE_USER",
    name: "Site Store User",
    description: "Receives project material at a site store.",
    rank: 20,
    permissions: [
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.GRN_POST,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.STORE_ISSUE,
      P.STACKING_RECORD,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_UPLOAD,
      P.INSPECTION_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "ADMIN_FLOOR_MANAGER",
    name: "Admin / Floor Manager",
    description: "Office administration, gate passes, office store and petty cash.",
    rank: 35,
    permissions: [
      ...REQUESTER_BASE,
      P.GATE_PASS_VIEW,
      P.GATE_PASS_CREATE,
      P.RECEIVE_GOODS,
      P.RECEIVING_VIEW,
      P.GRN_VIEW,
      P.GRN_CREATE,
      P.PO_VIEW,
      P.INVENTORY_VIEW,
      P.STORE_ISSUE,
      P.ASSET_VIEW,
      P.ASSET_MANAGE,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "SECURITY",
    name: "Security",
    description: "Records vehicle arrival and inward gate passes at the gate.",
    rank: 10,
    permissions: [P.GATE_PASS_VIEW, P.GATE_PASS_CREATE, P.PO_VIEW, P.DOCUMENT_UPLOAD, P.DOCUMENT_VIEW],
  },
  {
    code: "AUDIT_USER",
    name: "Audit User",
    description: "Read-only across the system plus audit review of vendor and disposal cases.",
    rank: 55,
    permissions: [
      P.PR_VIEW,
      P.PR_VIEW_ALL,
      P.RFQ_VIEW,
      P.QUOTE_VIEW,
      P.COMPARATIVE_VIEW,
      P.PO_VIEW,
      P.GRN_VIEW,
      P.RECEIVING_VIEW,
      P.INSPECTION_VIEW,
      P.GATE_PASS_VIEW,
      P.INVOICE_VIEW,
      P.INVENTORY_VIEW,
      P.ASSET_VIEW,
      P.DISPOSAL_VIEW,
      P.DISPOSAL_AUDIT_REVIEW,
      P.VENDOR_VIEW,
      P.VENDOR_AUDIT_REVIEW,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_VIEW,
      P.AUDIT_VIEW,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.EXPORT_DATA,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.DOCUMENT_VIEW_RESTRICTED,
      P.EXCEPTION_VIEW,
      P.PETTY_CASH_VIEW,
    ],
  },
  {
    code: "PM_USER",
    name: "PM User",
    description: "Project manager raising and validating ZD Material Demands.",
    rank: 40,
    permissions: [
      ...REQUESTER_BASE,
      P.PR_VIEW_ALL,
      P.PR_APPROVE,
      P.PR_RETURN,
      P.PR_CLARIFY,
      P.RFQ_VIEW,
      P.QUOTE_VIEW,
      P.COMPARATIVE_VIEW,
      P.PO_VIEW,
      P.GRN_VIEW,
      P.RECEIVING_VIEW,
      P.INSPECTION_VIEW,
      P.INSPECTION_PERFORM,
      P.VENDOR_VIEW,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.ANALYTICS_VIEW,
      P.EXCEPTION_VIEW,
      P.ASSET_VIEW,
    ],
  },
  {
    code: "DESIGN_USER",
    name: "Design User",
    description: "Design team validating specifications, BOQs and drawings.",
    rank: 25,
    permissions: [
      ...REQUESTER_BASE,
      P.PR_VIEW_ALL,
      P.PR_CLARIFY,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.INSPECTION_VIEW,
      P.INSPECTION_PERFORM,
      P.VENDOR_VIEW,
    ],
  },
  {
    code: "IT_USER",
    name: "IT User",
    description: "IT department: specifies and inspects IT equipment.",
    rank: 30,
    permissions: [
      ...REQUESTER_BASE,
      P.PR_VIEW_ALL,
      P.INSPECTION_VIEW,
      P.INSPECTION_PERFORM,
      P.ASSET_VIEW,
      P.ASSET_MANAGE,
      P.COMPARATIVE_VIEW,
      P.QUOTE_VIEW,
      P.PO_VIEW,
      P.VENDOR_VIEW,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.DISPOSAL_CREATE,
      P.DISPOSAL_VIEW,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "MANAGEMENT_COMMITTEE",
    name: "Management Committee Member",
    description: "Executive oversight, disposal sign-off and portfolio analytics.",
    rank: 90,
    permissions: [
      P.PR_VIEW,
      P.PR_VIEW_ALL,
      P.PO_VIEW,
      P.RFQ_VIEW,
      P.QUOTE_VIEW,
      P.COMPARATIVE_VIEW,
      P.GRN_VIEW,
      P.INVOICE_VIEW,
      P.INVENTORY_VIEW,
      P.VENDOR_VIEW,
      P.VENDOR_FINANCIALS_VIEW,
      P.CPC_VIEW,
      P.CPC_DECIDE,
      P.ASSET_VIEW,
      P.DISPOSAL_VIEW,
      P.DISPOSAL_MANAGEMENT_APPROVE,
      P.ANALYTICS_VIEW,
      P.ANALYTICS_VIEW_ALL_ENTITIES,
      P.EXPORT_DATA,
      P.AUDIT_VIEW,
      P.DOCUMENT_VIEW,
      P.DOCUMENT_VIEW_CONFIDENTIAL,
      P.EXCEPTION_VIEW,
    ],
  },
  {
    code: "SYSTEM_ADMIN",
    name: "System Administrator",
    description: "Full system access including configuration and RBAC.",
    rank: 100,
    permissions: ALL_PERMISSIONS as unknown as string[],
  },
];

export function permissionsForRoles(roleCodes: string[]): Set<string> {
  const out = new Set<string>();
  for (const rc of roleCodes) {
    const def = ROLE_DEFINITIONS.find((r) => r.code === rc);
    if (def) def.permissions.forEach((p) => out.add(p));
  }
  return out;
}
