import { prisma, type DbClient } from "@/lib/db";
import { CONFIG_KEYS, getConfigArray, getConfigNumber } from "@/lib/config";
import { RuleViolationError, ValidationError } from "@/lib/errors";
import { PERMISSIONS as P } from "@/lib/permissions";
import { userHasPermission, type SessionUser } from "@/lib/rbac";
import { round2 } from "@/lib/format";
import { consumption } from "./replenishment";
import { createRequirement, type RequirementLineInput } from "./requirements";

/**
 * Monthly repeat orders.
 *
 * ZAM/PUR/SOP-01 §4.1:
 *
 * > Repeating items demands are processed on monthly basis. "Requisitions" are
 * > generated by procurement (IT equipment) and logistics team (only grocery &
 * > house-keeping) after compiling **projected requirements for the whole next
 * > month** with the objective to carry reserve stock to avoid stock out, to
 * > stabilize fluctuation in consumption, to have adequate materials on hand
 * > when needed, to minimize the inventory investment, to operate efficiently
 * > etc. Monthly requisitions will comprise the requirement of general supplies
 * > like Grocery, housekeeping, stationery and IT accessories.
 *
 * The clause names four things the system can now do and could not before:
 * *projected* requirements, for the *whole next month*, for a *named set of
 * categories*, compiled by a *named owner* per category.
 *
 * ## The projection
 *
 * Average consumption over a window, scaled to the coming month, less what is
 * already on the shelf, less what is already on order. The last two are what
 * stop the proposal double-buying what somebody bought last week — a projection
 * that ignores open orders is how a store ends up with three months of paper.
 *
 * ## What it deliberately does not do
 *
 * **It does not submit.** §4.1 says requisitions are *generated* by the named
 * team, and a requisition nobody chose to raise is a commitment nobody owns. The
 * proposal produces a **draft**, with every line's arithmetic visible, and a
 * person decides.
 *
 * **It does not invent a quantity for an item with no history.** An item issued
 * twice in six months has no monthly pattern, and a proposal built on that would
 * be a guess wearing a forecast's clothes. Such items are listed with the reason
 * instead, so somebody can add them by hand if they know something the ledger
 * does not.
 *
 * **It does not decide who owns stationery.** §4.1 names procurement for IT
 * equipment and logistics for grocery and housekeeping, then lists stationery
 * among the monthly categories without naming an owner. That gap is in the
 * policy configuration as `null` — see PC-026 — and it shows here as
 * unassigned rather than being quietly given to one of the two teams.
 */

export type ProposalLine = {
  itemId: string;
  sku: string;
  name: string;
  categoryName: string | null;
  ownerRole: string | null;
  unit: string;
  /** Average monthly consumption from the ledger. */
  perMonth: number;
  /** How many separate issues that average rests on. */
  movements: number;
  onHand: number;
  reserved: number;
  onOrder: number;
  /** perMonth + cover − available − onOrder, floored at zero. */
  suggestedQty: number;
  estimatedUnitCost: number | null;
  estimatedValue: number;
  /** Set when no figure could be projected, and why. */
  withheld: string | null;
};

export type Proposal = {
  periodLabel: string;
  windowDays: number;
  coverDays: number;
  minMovements: number;
  categories: Array<{ name: string; ownerRole: string | null }>;
  /**
   * Categories §4.1 names that no catalogue category answers to.
   *
   * Reported rather than dropped. The clause names "Grocery, housekeeping,
   * stationery and IT accessories"; the catalogue calls the nearest things
   * "Pantry & Housekeeping", "Office Supplies" and "IT Peripherals &
   * Consumables". Guessing which policy word means which category would put a
   * mapping nobody chose behind every monthly order, so the mismatch is shown
   * and somebody decides.
   */
  unmatchedCategories: Array<{ name: string; ownerRole: string | null }>;
  lines: ProposalLine[];
  withheld: ProposalLine[];
  /** Lines whose category has no owner named in policy. */
  unassigned: ProposalLine[];
  totalValue: number;
};

/**
 * Builds the projection for the coming month.
 *
 * Read-only. Nothing is created until somebody asks for a draft.
 */
export async function monthlyProposal(
  filter: { entityId?: string | null; storeId?: string | null; ownerRole?: string | null } = {},
  db: DbClient = prisma,
): Promise<Proposal> {
  // §4.1's own list of monthly categories, with the owner each is assigned to.
  // Stationery is deliberately null — the clause lists it without naming a team.
  const owners = await getConfigArray<{ category: string; ownerRole: string | null }>(
    CONFIG_KEYS.POLICY_MONTHLY_REQUISITION_OWNERS,
    filter.entityId ?? null,
    db,
  );
  const windowDays = await getConfigNumber(
    CONFIG_KEYS.MIN_STOCK_WINDOW_DAYS,
    filter.entityId ?? null,
    db,
  );
  const coverDays = await getConfigNumber(
    CONFIG_KEYS.MIN_STOCK_SAFETY_DAYS,
    filter.entityId ?? null,
    db,
  );
  const minMovements = await getConfigNumber(
    CONFIG_KEYS.MIN_STOCK_MIN_MOVEMENTS,
    filter.entityId ?? null,
    db,
  );

  const wanted = filter.ownerRole
    ? owners.filter((o) => o.ownerRole === filter.ownerRole)
    : owners;

  const next = new Date();
  next.setMonth(next.getMonth() + 1);
  const periodLabel = `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, "0")}`;

  if (!wanted.length) {
    return {
      periodLabel,
      windowDays,
      coverDays,
      minMovements,
      categories: [],
      unmatchedCategories: [],
      lines: [],
      withheld: [],
      unassigned: [],
      totalValue: 0,
    };
  }

  // Categories are named in policy by their display name, so they are matched by
  // name. Case-insensitively, because a policy written by hand will not match a
  // seeded category's capitalisation and silently returning nothing would look
  // like there is no monthly demand at all.
  const categories = await db.category.findMany({
    select: { id: true, name: true, code: true },
  });
  const matched = wanted
    .map((o) => ({
      owner: o,
      category: categories.find(
        (c) =>
          c.name.toLowerCase() === o.category.toLowerCase() ||
          c.name.toLowerCase().includes(o.category.toLowerCase()),
      ),
    }))
    .filter((m) => m.category);

  const unmatchedCategories = wanted
    .filter((o) => !matched.some((m) => m.owner.category === o.category))
    .map((o) => ({ name: o.category, ownerRole: o.ownerRole }));

  const categoryIds = matched.map((m) => m.category!.id);
  if (!categoryIds.length) {
    return {
      periodLabel,
      windowDays,
      coverDays,
      minMovements,
      categories: wanted.map((o) => ({ name: o.category, ownerRole: o.ownerRole })),
      unmatchedCategories,
      lines: [],
      withheld: [],
      unassigned: [],
      totalValue: 0,
    };
  }

  const items = await db.item.findMany({
    where: { active: true, categoryId: { in: categoryIds } },
    select: {
      id: true,
      sku: true,
      name: true,
      unit: true,
      standardPrice: true,
      categoryId: true,
      category: { select: { name: true } },
    },
    take: 2000,
  });
  if (!items.length) {
    return {
      periodLabel,
      windowDays,
      coverDays,
      minMovements,
      categories: matched.map((m) => ({ name: m.category!.name, ownerRole: m.owner.ownerRole })),
      unmatchedCategories,
      lines: [],
      withheld: [],
      unassigned: [],
      totalValue: 0,
    };
  }

  const itemIds = items.map((i) => i.id);

  // Consumption, stock on hand and what is already on order — three grouped
  // reads rather than three per item.
  const [stats, buckets, onOrder] = await Promise.all([
    consumption({ itemIds, storeId: filter.storeId, days: windowDays }, db),
    db.inventoryItem.groupBy({
      by: ["itemId"],
      where: {
        itemId: { in: itemIds },
        ...(filter.storeId ? { storeId: filter.storeId } : {}),
      },
      _sum: { quantity: true, reservedQty: true },
    }),
    // Ordered but not yet received. A projection that ignores this is how a
    // store ends up with three months of paper.
    db.purchaseOrderItem.groupBy({
      by: ["itemId"],
      where: {
        itemId: { in: itemIds },
        po: { status: { in: ["ISSUED", "PARTIALLY_RECEIVED"] } },
      },
      _sum: { quantity: true, receivedQty: true },
    }),
  ]);

  const stockBy = new Map(
    buckets.map((b) => [
      b.itemId,
      { onHand: round2(b._sum.quantity ?? 0), reserved: round2(b._sum.reservedQty ?? 0) },
    ]),
  );
  const orderBy = new Map(
    onOrder.map((o) => [
      o.itemId,
      round2(Math.max(0, (o._sum.quantity ?? 0) - (o._sum.receivedQty ?? 0))),
    ]),
  );
  const ownerByCategory = new Map(
    matched.map((m) => [m.category!.id, m.owner.ownerRole ?? null]),
  );

  const all: ProposalLine[] = items.map((item) => {
    const s = stats.get(item.id);
    const stock = stockBy.get(item.id) ?? { onHand: 0, reserved: 0 };
    const ordered = orderBy.get(item.id) ?? 0;
    const available = round2(stock.onHand - stock.reserved);
    const perMonth = s?.perMonth ?? 0;
    const movements = s?.movements ?? 0;

    const base: ProposalLine = {
      itemId: item.id,
      sku: item.sku,
      name: item.name,
      categoryName: item.category?.name ?? null,
      ownerRole: ownerByCategory.get(item.categoryId) ?? null,
      unit: item.unit,
      perMonth,
      movements,
      onHand: stock.onHand,
      reserved: stock.reserved,
      onOrder: ordered,
      suggestedQty: 0,
      estimatedUnitCost: item.standardPrice ?? null,
      estimatedValue: 0,
      withheld: null,
    };

    if (movements === 0) {
      return { ...base, withheld: `No issues in the last ${windowDays} days.` };
    }
    if (movements < minMovements) {
      return {
        ...base,
        withheld: `Only ${movements} issue${movements === 1 ? "" : "s"} in ${windowDays} days — no monthly pattern to project from.`,
      };
    }

    // A month of consumption, plus the safety cover, less what is already there
    // and already coming.
    const target = round2(perMonth + (perMonth / 30) * coverDays);
    const suggested = round2(Math.max(0, target - available - ordered));
    return {
      ...base,
      suggestedQty: suggested,
      estimatedValue: round2(suggested * (item.standardPrice ?? 0)),
    };
  });

  const lines = all.filter((l) => !l.withheld && l.suggestedQty > 0);
  const withheld = all.filter((l) => l.withheld);
  const unassigned = lines.filter((l) => !l.ownerRole);

  lines.sort((a, b) => b.estimatedValue - a.estimatedValue || b.suggestedQty - a.suggestedQty);

  return {
    periodLabel,
    windowDays,
    coverDays,
    minMovements,
    categories: matched.map((m) => ({ name: m.category!.name, ownerRole: m.owner.ownerRole })),
    unmatchedCategories,
    lines,
    withheld,
    unassigned,
    totalValue: round2(lines.reduce((a, l) => a + l.estimatedValue, 0)),
  };
}

/**
 * Turns a proposal into a draft requirement.
 *
 * A **draft**, deliberately. §4.1 says requisitions are generated by the named
 * team, and one nobody chose to raise is a commitment nobody owns — so this
 * creates it unsubmitted with the projection's arithmetic in the justification,
 * and a person reviews and submits.
 *
 * The caller passes the lines it wants, which are checked against a freshly
 * computed proposal rather than trusted. A quantity posted from a browser is not
 * evidence of anything, and letting one through would turn a projection into a
 * free-text order form.
 */
export async function draftMonthlyRequirement(
  user: SessionUser,
  input: {
    entityId: string;
    departmentId: string;
    storeId?: string | null;
    ownerRole?: string | null;
    itemIds: string[];
    title?: string | null;
  },
  db: DbClient = prisma,
) {
  if (!userHasPermission(user, P.REQUIREMENT_CREATE)) {
    throw new RuleViolationError("You do not have permission to raise requirements.");
  }
  if (!input.itemIds?.length) throw new ValidationError("Choose at least one line to include.");

  const proposal = await monthlyProposal(
    { entityId: input.entityId, storeId: input.storeId, ownerRole: input.ownerRole },
    db,
  );
  const byId = new Map(proposal.lines.map((l) => [l.itemId, l]));

  const chosen = input.itemIds
    .map((id) => byId.get(id))
    .filter((l): l is ProposalLine => !!l && l.suggestedQty > 0);

  if (!chosen.length) {
    throw new RuleViolationError(
      "None of the chosen lines has a projected quantity any more. The projection is recomputed when the draft is created, " +
        "so stock received or ordered since the proposal was displayed has already been taken into account.",
    );
  }

  const items: RequirementLineInput[] = chosen.map((l) => ({
    itemId: l.itemId,
    description: l.name,
    quantity: l.suggestedQty,
    unit: l.unit,
    estimatedUnitCost: l.estimatedUnitCost,
    specification: null,
  }));

  // The arithmetic goes in the justification, so whoever reviews the draft can
  // see where each figure came from rather than being asked to trust it.
  const justification =
    `Projected from ${proposal.windowDays} days of issue history for ${proposal.periodLabel}, ` +
    `plus ${proposal.coverDays} days of cover, less stock on hand and quantities already on order.\n` +
    chosen
      .map(
        (l) =>
          `  ${l.sku}: ${l.perMonth}/month over ${l.movements} issues · ${l.onHand} on hand ` +
          `(${l.reserved} reserved) · ${l.onOrder} on order → ${l.suggestedQty} ${l.unit}`,
      )
      .join("\n");

  const required = new Date();
  required.setMonth(required.getMonth() + 1);
  required.setDate(1);

  return createRequirement(
    user,
    {
      entityId: input.entityId,
      departmentId: input.departmentId,
      title: input.title?.trim() || `Monthly repeat requirement — ${proposal.periodLabel}`,
      purpose:
        "ZAM/PUR/SOP-01 §4.1 monthly repeat order: reserve stock to avoid stock-out and stabilise fluctuation in consumption.",
      justification,
      priority: "NORMAL",
      requiredDate: required,
      storeId: input.storeId ?? null,
      items,
      // Never submitted. The SOP has the team generate the requisition; the
      // system proposing one is not the same as the team raising it.
      submit: false,
    },
    db,
  );
}
