/**
 * Static master data for the Heimdall seed.
 * Kept separate from the orchestration so the shapes stay readable.
 */

export const ENTITIES = [
  {
    code: "ZM",
    name: "Zameen Media",
    legalName: "Zameen Media (Private) Limited",
    city: "Lahore",
    address: "Zameen Tower, 96-B/1, M.M. Alam Road, Gulberg III, Lahore",
    taxNumber: "0712345-6",
    logoText: "ZM",
  },
  {
    code: "ZD",
    name: "Zameen Developments",
    legalName: "Zameen Developments (Private) Limited",
    city: "Lahore",
    address: "Zameen Developments, Main Boulevard, Gulberg, Lahore",
    taxNumber: "0798765-4",
    logoText: "ZD",
  },
] as const;

export const DEPARTMENTS: Array<{
  entity: "ZM" | "ZD";
  code: string;
  name: string;
  costCenter: string;
}> = [
  { entity: "ZM", code: "ADMIN", name: "Administration", costCenter: "ZM-CC-100" },
  { entity: "ZM", code: "IT", name: "Information Technology", costCenter: "ZM-CC-110" },
  { entity: "ZM", code: "MKT", name: "Marketing", costCenter: "ZM-CC-120" },
  { entity: "ZM", code: "SALES", name: "Sales", costCenter: "ZM-CC-130" },
  { entity: "ZM", code: "HR", name: "Human Resources", costCenter: "ZM-CC-140" },
  { entity: "ZM", code: "FIN", name: "Finance", costCenter: "ZM-CC-150" },
  { entity: "ZM", code: "SCM", name: "Supply Chain", costCenter: "ZM-CC-160" },
  { entity: "ZD", code: "PROJ", name: "Projects", costCenter: "ZD-CC-200" },
  { entity: "ZD", code: "DESIGN", name: "Design & Architecture", costCenter: "ZD-CC-210" },
  { entity: "ZD", code: "MEP", name: "MEP Engineering", costCenter: "ZD-CC-220" },
  { entity: "ZD", code: "SCM", name: "Supply Chain", costCenter: "ZD-CC-230" },
  { entity: "ZD", code: "ADMIN", name: "Administration", costCenter: "ZD-CC-240" },
  { entity: "ZD", code: "FIN", name: "Finance", costCenter: "ZD-CC-250" },
  { entity: "ZD", code: "QS", name: "Quantity Surveying", costCenter: "ZD-CC-260" },
];

export const PROJECTS = [
  {
    entity: "ZD" as const,
    code: "ZD-OPL",
    name: "Opal Mall & Luxury Suites",
    city: "Lahore",
    budget: 4_800_000_000,
    status: "Active",
  },
  {
    entity: "ZD" as const,
    code: "ZD-PRK",
    name: "Park View Corporate Tower",
    city: "Lahore",
    budget: 2_650_000_000,
    status: "Active",
  },
  {
    entity: "ZD" as const,
    code: "ZD-RES",
    name: "Residencia Phase II Infrastructure",
    city: "Islamabad",
    budget: 1_900_000_000,
    status: "Active",
  },
];

export const SITES = [
  { entity: "ZD" as const, code: "SITE-OPL", name: "Opal Mall Construction Site", project: "ZD-OPL", city: "Lahore", address: "Plot 12, Main Boulevard, Gulberg III, Lahore" },
  { entity: "ZD" as const, code: "SITE-PRK", name: "Park View Tower Site", project: "ZD-PRK", city: "Lahore", address: "Ferozepur Road, Lahore" },
  { entity: "ZD" as const, code: "SITE-RES", name: "Residencia Phase II Site", project: "ZD-RES", city: "Islamabad", address: "Zone V, Islamabad" },
];

export const STORES = [
  { entity: "ZD" as const, code: "WH-MULTAN", name: "Central Warehouse — Multan Road", kind: "CENTRAL_WAREHOUSE", city: "Lahore", address: "Multan Road, Lahore", site: null, project: null },
  { entity: "ZD" as const, code: "ST-OPL", name: "Opal Mall Site Store", kind: "SITE_STORE", city: "Lahore", address: "Plot 12, Main Boulevard, Gulberg III", site: "SITE-OPL", project: "ZD-OPL" },
  { entity: "ZD" as const, code: "ST-PRK", name: "Park View Tower Site Store", kind: "SITE_STORE", city: "Lahore", address: "Ferozepur Road, Lahore", site: "SITE-PRK", project: "ZD-PRK" },
  { entity: "ZD" as const, code: "ST-RES", name: "Residencia Phase II Site Store", kind: "SITE_STORE", city: "Islamabad", address: "Zone V, Islamabad", site: "SITE-RES", project: "ZD-RES" },
  { entity: "ZD" as const, code: "ST-ZD-OFF", name: "ZD Head Office Store", kind: "OFFICE_STORE", city: "Lahore", address: "Main Boulevard, Gulberg", site: null, project: null },
  { entity: "ZM" as const, code: "ST-ZM-HO", name: "Zameen Tower Office Store", kind: "OFFICE_STORE", city: "Lahore", address: "Zameen Tower, M.M. Alam Road", site: null, project: null },
  { entity: "ZM" as const, code: "ST-ZM-IT", name: "IT Asset Store", kind: "OTHER", city: "Lahore", address: "Zameen Tower, 4th Floor", site: null, project: null },
  { entity: "ZM" as const, code: "ST-ZM-KHI", name: "Karachi Office Store", kind: "OFFICE_STORE", city: "Karachi", address: "Shahrah-e-Faisal, Karachi", site: null, project: null },
];

export const STORE_LOCATIONS: Array<{ store: string; label: string; zone: string; rack: string; bin: string; handling: string }> = [
  { store: "WH-MULTAN", label: "A-01-01", zone: "A", rack: "01", bin: "01", handling: "GENERAL" },
  { store: "WH-MULTAN", label: "A-01-02", zone: "A", rack: "01", bin: "02", handling: "GENERAL" },
  { store: "WH-MULTAN", label: "B-02-01", zone: "B", rack: "02", bin: "01", handling: "PROJECT_MATERIAL" },
  { store: "WH-MULTAN", label: "B-02-02", zone: "B", rack: "02", bin: "02", handling: "PROJECT_MATERIAL" },
  { store: "WH-MULTAN", label: "C-YARD-01", zone: "C", rack: "YARD", bin: "01", handling: "PROJECT_MATERIAL" },
  { store: "WH-MULTAN", label: "V-01-01", zone: "V", rack: "01", bin: "01", handling: "HIGH_VALUE" },
  { store: "WH-MULTAN", label: "H-01-01", zone: "H", rack: "01", bin: "01", handling: "HAZARDOUS" },
  { store: "ST-OPL", label: "YARD-A", zone: "YARD", rack: "A", bin: "01", handling: "PROJECT_MATERIAL" },
  { store: "ST-OPL", label: "YARD-B", zone: "YARD", rack: "B", bin: "01", handling: "PROJECT_MATERIAL" },
  { store: "ST-OPL", label: "COV-01", zone: "COVERED", rack: "01", bin: "01", handling: "SENSITIVE" },
  { store: "ST-PRK", label: "YARD-A", zone: "YARD", rack: "A", bin: "01", handling: "PROJECT_MATERIAL" },
  { store: "ST-PRK", label: "COV-01", zone: "COVERED", rack: "01", bin: "01", handling: "GENERAL" },
  { store: "ST-RES", label: "YARD-A", zone: "YARD", rack: "A", bin: "01", handling: "PROJECT_MATERIAL" },
  { store: "ST-ZM-HO", label: "STA-01", zone: "STATIONERY", rack: "01", bin: "01", handling: "GENERAL" },
  { store: "ST-ZM-HO", label: "STA-02", zone: "STATIONERY", rack: "01", bin: "02", handling: "GENERAL" },
  { store: "ST-ZM-HO", label: "PNT-01", zone: "PANTRY", rack: "01", bin: "01", handling: "GENERAL" },
  { store: "ST-ZM-IT", label: "IT-SEC-01", zone: "SECURE", rack: "01", bin: "01", handling: "HIGH_VALUE" },
  { store: "ST-ZM-IT", label: "IT-SEC-02", zone: "SECURE", rack: "01", bin: "02", handling: "HIGH_VALUE" },
  { store: "ST-ZM-KHI", label: "KHI-01", zone: "A", rack: "01", bin: "01", handling: "GENERAL" },
  { store: "ST-ZD-OFF", label: "ZD-OFF-01", zone: "A", rack: "01", bin: "01", handling: "GENERAL" },
];

export const CATEGORIES: Array<{
  code: string;
  name: string;
  requiresInspection: boolean;
  defaultDisposition: string;
  assetTagRequired: boolean;
  entity?: "ZM" | "ZD";
}> = [
  { code: "IT-EQUIP", name: "IT Equipment", requiresInspection: true, defaultDisposition: "ASSET", assetTagRequired: true },
  { code: "IT-PERIPH", name: "IT Peripherals & Consumables", requiresInspection: false, defaultDisposition: "INVENTORY", assetTagRequired: false },
  { code: "OFF-SUPPLY", name: "Office Supplies", requiresInspection: false, defaultDisposition: "CONSUMABLE", assetTagRequired: false },
  { code: "FURN", name: "Furniture & Fixtures", requiresInspection: false, defaultDisposition: "ASSET", assetTagRequired: true },
  { code: "MKT-MAT", name: "Marketing Material", requiresInspection: false, defaultDisposition: "EXPENSE", assetTagRequired: false },
  { code: "HVAC", name: "HVAC & Air Conditioning", requiresInspection: true, defaultDisposition: "ASSET", assetTagRequired: true },
  { code: "CONSTR-STEEL", name: "Construction — Steel & Rebar", requiresInspection: true, defaultDisposition: "PROJECT_MATERIAL", assetTagRequired: false },
  { code: "CONSTR-CEMENT", name: "Construction — Cement & Aggregate", requiresInspection: true, defaultDisposition: "PROJECT_MATERIAL", assetTagRequired: false },
  { code: "CONSTR-BLOCK", name: "Construction — Blocks & Masonry", requiresInspection: false, defaultDisposition: "PROJECT_MATERIAL", assetTagRequired: false },
  { code: "FITOUT", name: "Fit-out & Finishes", requiresInspection: false, defaultDisposition: "PROJECT_MATERIAL", assetTagRequired: false },
  { code: "MEP-ELEC", name: "MEP — Electrical", requiresInspection: true, defaultDisposition: "PROJECT_MATERIAL", assetTagRequired: false },
  { code: "MEP-PLUMB", name: "MEP — Plumbing", requiresInspection: false, defaultDisposition: "PROJECT_MATERIAL", assetTagRequired: false },
  { code: "MACHINERY", name: "Machinery & Equipment", requiresInspection: true, defaultDisposition: "ASSET", assetTagRequired: true },
  { code: "SAFETY", name: "Safety & PPE", requiresInspection: false, defaultDisposition: "INVENTORY", assetTagRequired: false },
  { code: "SERVICES", name: "Professional Services", requiresInspection: false, defaultDisposition: "EXPENSE", assetTagRequired: false },
  { code: "VEHICLE", name: "Vehicles & Transport", requiresInspection: true, defaultDisposition: "ASSET", assetTagRequired: true },
  { code: "PANTRY", name: "Pantry & Housekeeping", requiresInspection: false, defaultDisposition: "CONSUMABLE", assetTagRequired: false },
];

export const ITEMS: Array<{
  sku: string;
  name: string;
  category: string;
  unit: string;
  brand?: string;
  model?: string;
  make?: string;
  specification?: string;
  standardPrice?: number;
  trackSerial?: boolean;
  trackBatch?: boolean;
  trackExpiry?: boolean;
  reorderLevel?: number;
}> = [
  { sku: "IT-LAP-0001", name: "Business Laptop — 14\" i7", category: "IT-EQUIP", unit: "EA", brand: "Dell", model: "Latitude 5450", make: "Dell Technologies", specification: "Intel Core i7-1355U, 16GB DDR5, 512GB NVMe SSD, 14\" FHD, Windows 11 Pro, 3-year onsite warranty", standardPrice: 385000, trackSerial: true, reorderLevel: 5 },
  { sku: "IT-LAP-0002", name: "Design Workstation Laptop — 16\"", category: "IT-EQUIP", unit: "EA", brand: "HP", model: "ZBook Firefly 16 G11", make: "HP Inc.", specification: "Intel Core Ultra 7, 32GB, 1TB NVMe, RTX A500 4GB, 16\" WUXGA, Windows 11 Pro", standardPrice: 612000, trackSerial: true, reorderLevel: 2 },
  { sku: "IT-PRN-0001", name: "Multifunction Laser Printer A3", category: "IT-EQUIP", unit: "EA", brand: "Canon", model: "imageRUNNER 2630i", specification: "A3 mono MFP, 30ppm, duplex, network, ADF 100 sheets, 1-year warranty", standardPrice: 465000, trackSerial: true, reorderLevel: 1 },
  { sku: "IT-PRN-0002", name: "Desktop Laser Printer A4", category: "IT-EQUIP", unit: "EA", brand: "HP", model: "LaserJet Pro M404dn", specification: "A4 mono, 38ppm, duplex, ethernet", standardPrice: 78000, trackSerial: true, reorderLevel: 2 },
  { sku: "IT-MON-0001", name: "24\" IPS Monitor", category: "IT-EQUIP", unit: "EA", brand: "Dell", model: "P2422H", specification: "23.8\" FHD IPS, HDMI/DP, height adjustable", standardPrice: 62000, trackSerial: true, reorderLevel: 6 },
  { sku: "IT-TON-0001", name: "Toner Cartridge — CF259A", category: "IT-PERIPH", unit: "EA", brand: "HP", model: "CF259A", specification: "Black, 3000 pages yield", standardPrice: 14500, reorderLevel: 10 },
  { sku: "IT-UPS-0001", name: "Online UPS 3kVA", category: "IT-EQUIP", unit: "EA", brand: "APC", model: "SRV3KI", specification: "3kVA/2.4kW online double conversion, rack/tower", standardPrice: 285000, trackSerial: true, reorderLevel: 1 },
  { sku: "OFF-PAP-0001", name: "A4 Copier Paper 80gsm", category: "OFF-SUPPLY", unit: "REAM", brand: "Double A", specification: "A4, 80gsm, 500 sheets per ream", standardPrice: 1320, reorderLevel: 120 },
  { sku: "OFF-PEN-0001", name: "Ball Point Pen — Blue", category: "OFF-SUPPLY", unit: "BOX", brand: "Piano", specification: "Box of 50, blue ink, 0.7mm", standardPrice: 850, reorderLevel: 30 },
  { sku: "OFF-FIL-0001", name: "Box File — Foolscap", category: "OFF-SUPPLY", unit: "EA", specification: "Board box file with lever arch, foolscap", standardPrice: 420, reorderLevel: 60 },
  { sku: "OFF-STA-0001", name: "Stapler — Heavy Duty", category: "OFF-SUPPLY", unit: "EA", brand: "Kangaro", model: "HD-45", specification: "Up to 45 sheets, metal body", standardPrice: 2100, reorderLevel: 12 },
  { sku: "OFF-WBM-0001", name: "Whiteboard Marker Set", category: "OFF-SUPPLY", unit: "SET", specification: "Set of 4 (black, blue, red, green), dry erase", standardPrice: 680, reorderLevel: 25 },
  { sku: "PAN-TEA-0001", name: "Tea Bags — 100s", category: "PANTRY", unit: "BOX", brand: "Lipton", specification: "Yellow label, 100 tea bags per box", standardPrice: 1150, reorderLevel: 40 },
  { sku: "PAN-CLN-0001", name: "Floor Cleaner 5L", category: "PANTRY", unit: "CAN", brand: "Harpic", specification: "5 litre concentrated floor cleaner", standardPrice: 1850, trackExpiry: true, reorderLevel: 15 },
  { sku: "FUR-CHR-0001", name: "Ergonomic Task Chair", category: "FURN", unit: "EA", brand: "Interwood", model: "Vista Mesh", specification: "Mesh back, adjustable lumbar, 4D armrest, gas lift, 5-year frame warranty", standardPrice: 68500, reorderLevel: 4 },
  { sku: "FUR-DSK-0001", name: "Workstation Desk 1400mm", category: "FURN", unit: "EA", brand: "Interwood", specification: "1400x700mm laminate top, cable tray, 25mm MDF, metal legs", standardPrice: 82000, reorderLevel: 3 },
  { sku: "FUR-CAB-0001", name: "Filing Cabinet — 4 Drawer", category: "FURN", unit: "EA", specification: "Steel, 4 drawer, central locking, powder coated", standardPrice: 54000, reorderLevel: 2 },
  { sku: "FUR-CNF-0001", name: "Conference Table 12-Seater", category: "FURN", unit: "EA", brand: "Interwood", specification: "3600x1200mm veneer top, cable management, powered ports", standardPrice: 385000 },
  { sku: "HVA-SPL-0001", name: "Split Air Conditioner 1.5 Ton Inverter", category: "HVAC", unit: "EA", brand: "Haier", model: "HSU-18HFCF", specification: "1.5 ton DC inverter, T3 compressor, R410a, heat & cool, 10-year compressor warranty", standardPrice: 178000, trackSerial: true, reorderLevel: 2 },
  { sku: "HVA-SPL-0002", name: "Split Air Conditioner 2.0 Ton Inverter", category: "HVAC", unit: "EA", brand: "Gree", model: "GS-24PITH11W", specification: "2.0 ton DC inverter, T3 compressor, WiFi control, heat & cool", standardPrice: 235000, trackSerial: true },
  { sku: "HVA-CAS-0001", name: "Cassette AC 4.0 Ton", category: "HVAC", unit: "EA", brand: "Mitsubishi", specification: "4 ton ceiling cassette, 4-way airflow, R410a", standardPrice: 685000, trackSerial: true },
  { sku: "CST-STL-0001", name: "Deformed Steel Bar Grade 60 — 16mm", category: "CONSTR-STEEL", unit: "TON", brand: "Amreli Steels", specification: "ASTM A615 Grade 60, 16mm dia, 40ft length, mill test certificate required", standardPrice: 268000, trackBatch: true, reorderLevel: 10 },
  { sku: "CST-STL-0002", name: "Deformed Steel Bar Grade 60 — 12mm", category: "CONSTR-STEEL", unit: "TON", brand: "Mughal Steel", specification: "ASTM A615 Grade 60, 12mm dia, 40ft length, mill test certificate required", standardPrice: 265000, trackBatch: true, reorderLevel: 8 },
  { sku: "CST-STL-0003", name: "Deformed Steel Bar Grade 60 — 20mm", category: "CONSTR-STEEL", unit: "TON", brand: "Amreli Steels", specification: "ASTM A615 Grade 60, 20mm dia, 40ft length", standardPrice: 271000, trackBatch: true },
  { sku: "CST-CEM-0001", name: "Ordinary Portland Cement 50kg", category: "CONSTR-CEMENT", unit: "BAG", brand: "Maple Leaf", specification: "OPC Type-I, 50kg bag, BS EN 197-1 compliant", standardPrice: 1385, trackBatch: true, reorderLevel: 500 },
  { sku: "CST-CEM-0002", name: "Sulphate Resistant Cement 50kg", category: "CONSTR-CEMENT", unit: "BAG", brand: "Bestway", specification: "SRC, 50kg bag, for foundations in aggressive soils", standardPrice: 1520, trackBatch: true },
  { sku: "CST-SND-0001", name: "Coarse Sand (Lawrencepur)", category: "CONSTR-CEMENT", unit: "CFT", specification: "Washed coarse sand, silt content < 3%", standardPrice: 95, reorderLevel: 2000 },
  { sku: "CST-CRS-0001", name: "Crush Aggregate 3/4\"", category: "CONSTR-CEMENT", unit: "CFT", specification: "Margalla crush, 3/4 inch nominal, washed", standardPrice: 145, reorderLevel: 2000 },
  { sku: "CST-BLK-0001", name: "Concrete Block 8\"", category: "CONSTR-BLOCK", unit: "EA", specification: "8x8x16 inch solid concrete block, min 1500psi", standardPrice: 118, reorderLevel: 3000 },
  { sku: "FIT-TIL-0001", name: "Porcelain Floor Tile 600x600", category: "FITOUT", unit: "SQFT", brand: "Master Tiles", specification: "600x600mm rectified porcelain, matte finish, PEI IV", standardPrice: 385, reorderLevel: 1500 },
  { sku: "FIT-GYP-0001", name: "Gypsum Board 12.5mm", category: "FITOUT", unit: "SHEET", brand: "Knauf", specification: "12.5mm x 1200 x 2400mm regular gypsum board", standardPrice: 2450, reorderLevel: 200 },
  { sku: "FIT-PNT-0001", name: "Emulsion Paint — Interior 3.64L", category: "FITOUT", unit: "GAL", brand: "Dulux", specification: "Weathershield interior matt emulsion, 3.64L", standardPrice: 6800, trackBatch: true, reorderLevel: 60 },
  { sku: "MEP-CBL-0001", name: "Copper Cable 3-Core 4mm²", category: "MEP-ELEC", unit: "M", brand: "Pakistan Cables", specification: "3x4mm² copper, PVC insulated, 600/1000V, IEC 60502", standardPrice: 1180, reorderLevel: 500 },
  { sku: "MEP-DBD-0001", name: "Distribution Board 12-Way", category: "MEP-ELEC", unit: "EA", brand: "Schneider", specification: "12-way TPN distribution board, IP42, with MCBs", standardPrice: 42500, trackSerial: true },
  { sku: "MEP-PPE-0001", name: "PPR Pipe 25mm PN20", category: "MEP-PLUMB", unit: "M", brand: "Popular", specification: "25mm PN20 PPR pipe, hot & cold water", standardPrice: 385, reorderLevel: 400 },
  { sku: "MKT-BRD-0001", name: "Billboard Panel Print", category: "MKT-MAT", unit: "SQFT", specification: "Flex print 440gsm, UV resistant, eyelets", standardPrice: 165 },
  { sku: "MKT-BRO-0001", name: "Project Brochure — 12pp A4", category: "MKT-MAT", unit: "EA", specification: "12 page A4, 170gsm art paper, matt lamination", standardPrice: 285 },
  { sku: "MKT-STD-0001", name: "Exhibition Standee 3x6ft", category: "MKT-MAT", unit: "EA", specification: "Roll-up standee, 3x6ft, aluminium base", standardPrice: 12500 },
  { sku: "SAF-HLM-0001", name: "Safety Helmet — Industrial", category: "SAFETY", unit: "EA", brand: "3M", specification: "ANSI Z89.1 Type I Class E, ratchet suspension", standardPrice: 2850, reorderLevel: 50 },
  { sku: "SAF-VST-0001", name: "Hi-Vis Safety Vest", category: "SAFETY", unit: "EA", specification: "Class 2 hi-vis, reflective tape, mesh", standardPrice: 1150, reorderLevel: 80 },
  { sku: "MAC-GEN-0001", name: "Diesel Generator 100kVA", category: "MACHINERY", unit: "EA", brand: "Perkins", model: "1104A-44TG2", specification: "100kVA prime, sound-proof canopy, ATS, 8-hour tank", standardPrice: 4850000, trackSerial: true },
  { sku: "MAC-VBR-0001", name: "Concrete Vibrator 5HP", category: "MACHINERY", unit: "EA", specification: "5HP petrol needle vibrator with 6m hose", standardPrice: 168000, trackSerial: true },
];

/** 20 criteria × max 3 = 60 achievable, matching the 30/60 operating rule. */
export const EVALUATION_CRITERIA = [
  { code: "MKT-REP", name: "Market reputation", group: "Standing", description: "Standing in the market and among peer buyers.", sequence: 1 },
  { code: "EXPERIENCE", name: "Relevant experience", group: "Standing", description: "Years and depth of experience in the required category.", sequence: 2 },
  { code: "CLIENT-REF", name: "Client references", group: "Standing", description: "Quality and verifiability of client references.", sequence: 3 },
  { code: "INT-REF", name: "Internal references", group: "Standing", description: "Prior experience of our own departments with this vendor.", sequence: 4 },
  { code: "COMPANY-STATUS", name: "Company status & registration", group: "Compliance", description: "Legal form, registration, tax status and filer standing.", sequence: 5 },
  { code: "CREDIT-FAC", name: "Credit facilities offered", group: "Commercial", description: "Willingness to extend credit and on what terms.", sequence: 6 },
  { code: "CREDIT-LINE", name: "Credit line size", group: "Commercial", description: "Size of the credit line relative to our expected spend.", sequence: 7 },
  { code: "PAYMENT-MODE", name: "Payment mode flexibility", group: "Commercial", description: "Flexibility on payment instruments and schedules.", sequence: 8 },
  { code: "PRICE", name: "Price competitiveness", group: "Commercial", description: "Pricing against the prevailing market rate.", sequence: 9 },
  { code: "MARKET-PRICING", name: "Market pricing transparency", group: "Commercial", description: "Transparency and stability of quoted pricing.", sequence: 10 },
  { code: "OFFICES", name: "Number of offices", group: "Capacity", description: "Office footprint supporting service delivery.", sequence: 11 },
  { code: "GEO-COVER", name: "Geographic coverage", group: "Capacity", description: "Cities and regions the vendor can actually serve.", sequence: 12 },
  { code: "WORKFORCE", name: "Workforce strength", group: "Capacity", description: "Permanent workforce available to service orders.", sequence: 13 },
  { code: "TRANSPORT", name: "Transportation capability", group: "Capacity", description: "Owned or contracted transport for delivery.", sequence: 14 },
  { code: "LEAD-TIME", name: "Delivery lead time", group: "Delivery", description: "Committed and demonstrated lead times.", sequence: 15 },
  { code: "QUALITY", name: "Product quality", group: "Delivery", description: "Consistency and standard of goods supplied.", sequence: 16 },
  { code: "REPLACEMENT", name: "Replacement policy", group: "After-sales", description: "Clarity and honouring of replacement commitments.", sequence: 17 },
  { code: "AFTER-SALES", name: "After-sales support", group: "After-sales", description: "Responsiveness after delivery and during warranty.", sequence: 18 },
  { code: "TECH-SUPPORT", name: "Technical support", group: "After-sales", description: "Availability of qualified technical support.", sequence: 19 },
  { code: "CUST-SERVICE", name: "Customer service", group: "After-sales", description: "Ease of dealing with the vendor day to day.", sequence: 20 },
];

export const DOCUMENT_TYPES = [
  { code: "PR-FORM", name: "Purchase Requisition", category: "Requisition", appliesTo: ["PR"], viewPermission: null },
  { code: "BOQ", name: "Bill of Quantities", category: "BOQ", appliesTo: ["PR"], viewPermission: null },
  { code: "DRAWING", name: "Drawing", category: "Drawing", appliesTo: ["PR"], viewPermission: null, allowedExtensions: "pdf,dwg,dxf,png,jpg" },
  { code: "TECH-SPEC", name: "Technical Specification", category: "Specification", appliesTo: ["PR", "RFQ"], viewPermission: null },
  { code: "RFQ-DOC", name: "RFQ Document", category: "RFQ", appliesTo: ["RFQ"], viewPermission: null },
  { code: "QUOTATION", name: "Vendor Quotation", category: "Quotation", appliesTo: ["QUOTE"], viewPermission: "document.view_confidential" },
  { code: "COMPARATIVE", name: "Comparative Statement", category: "Comparative", appliesTo: ["COMPARATIVE"], viewPermission: "document.view_confidential" },
  { code: "NEGOTIATION", name: "Negotiation Record", category: "Negotiation", appliesTo: ["COMPARATIVE", "QUOTE"], viewPermission: "document.view_confidential" },
  { code: "CPC-MINUTES", name: "CPC Decision / Minutes", category: "CPC", appliesTo: ["CPC"], viewPermission: "document.view_confidential" },
  { code: "PO-DOC", name: "Purchase Order", category: "PO", appliesTo: ["PO"], viewPermission: null },
  { code: "GATE-PASS", name: "Inward Gate Pass", category: "Gate Pass", appliesTo: ["GATE_PASS"], viewPermission: null },
  { code: "DELIVERY-NOTE", name: "Delivery Note / Challan", category: "Delivery", appliesTo: ["DELIVERY"], viewPermission: null },
  { code: "INSPECTION-FORM", name: "Inspection Form", category: "Inspection", appliesTo: ["INSPECTION"], viewPermission: null },
  { code: "MILL-CERT", name: "Mill / Test Certificate", category: "Certificate", appliesTo: ["DELIVERY", "INSPECTION", "GRN"], viewPermission: null },
  { code: "GRN-DOC", name: "Goods Receipt Note", category: "GRN", appliesTo: ["GRN"], viewPermission: null },
  { code: "INVOICE-DOC", name: "Vendor Invoice", category: "Invoice", appliesTo: ["INVOICE"], viewPermission: "document.view_confidential" },
  { code: "PAYMENT-DOC", name: "Payment Documentation", category: "Payment", appliesTo: ["INVOICE"], viewPermission: "document.view_confidential" },
  { code: "RECEIPT", name: "Cash Purchase Receipt", category: "Receipt", appliesTo: ["PETTY_CASH"], viewPermission: null },
  { code: "VOUCHER", name: "Petty Cash Voucher", category: "Voucher", appliesTo: ["PETTY_CASH"], viewPermission: null },
  { code: "VENDOR-PROFILE", name: "Vendor Company Profile", category: "Vendor", appliesTo: ["VENDOR"], viewPermission: null },
  { code: "NTN-CERT", name: "NTN Certificate", category: "Vendor", appliesTo: ["VENDOR"], viewPermission: "document.view_confidential" },
  { code: "STRN-CERT", name: "Sales Tax Registration", category: "Vendor", appliesTo: ["VENDOR"], viewPermission: "document.view_confidential" },
  { code: "BANK-LETTER", name: "Bank Details Letter", category: "Vendor", appliesTo: ["VENDOR"], viewPermission: "document.view_restricted" },
  { code: "VENDOR-EVAL", name: "Vendor Evaluation Sheet", category: "Vendor", appliesTo: ["VENDOR"], viewPermission: "document.view_confidential" },
  { code: "EVIDENCE", name: "Investigation Evidence", category: "Investigation", appliesTo: ["VENDOR"], viewPermission: "document.view_restricted" },
  { code: "DISPOSAL-DOC", name: "Disposal Documentation", category: "Disposal", appliesTo: ["DISPOSAL"], viewPermission: null },
  { code: "BID-DOC", name: "Disposal Bid", category: "Disposal", appliesTo: ["DISPOSAL"], viewPermission: "document.view_confidential" },
  { code: "ASSET-DOC", name: "Asset Documentation", category: "Asset", appliesTo: ["ASSET"], viewPermission: null },
  { code: "TRANSFER-DOC", name: "Store Transfer Note", category: "Transfer", appliesTo: ["STORE_TRANSFER"], viewPermission: null },
  { code: "OTHER", name: "Other Supporting Document", category: "General", appliesTo: ["PR", "PO", "GRN", "INVOICE", "VENDOR", "PETTY_CASH", "DISPOSAL", "ASSET"], viewPermission: null },
];

export type SeedUser = {
  email: string;
  name: string;
  title: string;
  roles: string[];
  entity: "ZM" | "ZD";
  entities?: Array<"ZM" | "ZD">;
  department?: string;
  phone?: string;
};

export const USERS: SeedUser[] = [
  // ── Executive / cross-entity ───────────────────────────────
  { email: "system.admin@zameen.com", name: "Sysadmin Operations", title: "System Administrator", roles: ["SYSTEM_ADMIN"], entity: "ZM", entities: ["ZM", "ZD"] },
  { email: "kamran.rasheed@zameen.com", name: "Kamran Rasheed", title: "Procurement Director", roles: ["PROCUREMENT_DIRECTOR"], entity: "ZM", entities: ["ZM", "ZD"], department: "SCM", phone: "+92 300 8412001" },
  { email: "nadia.saleem@zameen.com", name: "Nadia Saleem", title: "Chief Financial Officer", roles: ["FINANCE_APPROVER", "MANAGEMENT_COMMITTEE"], entity: "ZM", entities: ["ZM", "ZD"], department: "FIN", phone: "+92 300 8412002" },
  { email: "shahid.mahmood@zameen.com", name: "Shahid Mahmood", title: "Group Chief Operating Officer", roles: ["MANAGEMENT_COMMITTEE"], entity: "ZM", entities: ["ZM", "ZD"], phone: "+92 300 8412003" },
  { email: "faryal.qureshi@zameen.com", name: "Faryal Qureshi", title: "Head of Internal Audit", roles: ["AUDIT_USER"], entity: "ZM", entities: ["ZM", "ZD"], phone: "+92 300 8412004" },

  // ── ZM procurement ────────────────────────────────────────
  { email: "asim.javed@zameen.com", name: "Asim Javed", title: "Procurement Senior Manager", roles: ["PROCUREMENT_SENIOR_MANAGER"], entity: "ZM", entities: ["ZM", "ZD"], department: "SCM", phone: "+92 301 8412010" },
  { email: "hira.aslam@zameen.com", name: "Hira Aslam", title: "Procurement Officer — IT & Admin", roles: ["PROCUREMENT_OFFICER"], entity: "ZM", department: "SCM", phone: "+92 301 8412011" },
  { email: "usman.tariq@zameen.com", name: "Usman Tariq", title: "Buyer — General & Marketing", roles: ["BUYER"], entity: "ZM", department: "SCM", phone: "+92 301 8412012" },

  // ── ZM departments ────────────────────────────────────────
  { email: "bilal.hameed@zameen.com", name: "Bilal Hameed", title: "Head of Information Technology", roles: ["HOD", "IT_USER"], entity: "ZM", department: "IT", phone: "+92 302 8412020" },
  { email: "sana.iqbal@zameen.com", name: "Sana Iqbal", title: "IT Infrastructure Engineer", roles: ["IT_USER", "TECHNICAL_INSPECTOR"], entity: "ZM", department: "IT", phone: "+92 302 8412021" },
  { email: "adeel.rauf@zameen.com", name: "Adeel Rauf", title: "Head of Marketing", roles: ["HOD"], entity: "ZM", department: "MKT", phone: "+92 302 8412022" },
  { email: "mehwish.khan@zameen.com", name: "Mehwish Khan", title: "Marketing Executive", roles: ["REQUESTER"], entity: "ZM", department: "MKT", phone: "+92 302 8412023" },
  { email: "tahir.abbas@zameen.com", name: "Tahir Abbas", title: "Head of Administration", roles: ["HOD", "ADMIN_FLOOR_MANAGER"], entity: "ZM", department: "ADMIN", phone: "+92 302 8412024" },
  { email: "rabia.noor@zameen.com", name: "Rabia Noor", title: "Admin & Facilities Officer", roles: ["ADMIN_FLOOR_MANAGER"], entity: "ZM", department: "ADMIN", phone: "+92 302 8412025" },
  { email: "junaid.akhtar@zameen.com", name: "Junaid Akhtar", title: "Head of Sales", roles: ["HOD"], entity: "ZM", department: "SALES", phone: "+92 302 8412026" },
  { email: "ayesha.malik@zameen.com", name: "Ayesha Malik", title: "Head of Human Resources", roles: ["HOD"], entity: "ZM", department: "HR", phone: "+92 302 8412027" },

  // ── Finance ───────────────────────────────────────────────
  { email: "imran.shafiq@zameen.com", name: "Imran Shafiq", title: "Finance Manager — Payables", roles: ["FINANCE_USER"], entity: "ZM", entities: ["ZM", "ZD"], department: "FIN", phone: "+92 303 8412030" },
  { email: "zoya.hassan@zameen.com", name: "Zoya Hassan", title: "Accounts Payable Officer", roles: ["FINANCE_USER"], entity: "ZD", entities: ["ZM", "ZD"], department: "FIN", phone: "+92 303 8412031" },

  // ── ZM stores & security ──────────────────────────────────
  { email: "shakeel.ahmad@zameen.com", name: "Shakeel Ahmad", title: "Store Manager — Head Office", roles: ["STORE_MANAGER"], entity: "ZM", department: "ADMIN", phone: "+92 304 8412040" },
  { email: "waqas.ali@zameen.com", name: "Waqas Ali", title: "Store Receiver — Head Office", roles: ["STORE_RECEIVER"], entity: "ZM", department: "ADMIN", phone: "+92 304 8412041" },
  { email: "gate.security@zameen.com", name: "Riaz Masih", title: "Security Supervisor", roles: ["SECURITY"], entity: "ZM", entities: ["ZM", "ZD"], phone: "+92 304 8412042" },

  // ── ZD procurement & projects ─────────────────────────────
  { email: "farhan.siddiqui@zameen.com", name: "Farhan Siddiqui", title: "Supply Chain Manager — ZD", roles: ["PROCUREMENT_SENIOR_MANAGER"], entity: "ZD", department: "SCM", phone: "+92 305 8412050" },
  { email: "danish.raza@zameen.com", name: "Danish Raza", title: "Procurement Officer — Construction", roles: ["PROCUREMENT_OFFICER"], entity: "ZD", department: "SCM", phone: "+92 305 8412051" },
  { email: "saad.mirza@zameen.com", name: "Saad Mirza", title: "Buyer — Fit-out & MEP", roles: ["BUYER"], entity: "ZD", department: "SCM", phone: "+92 305 8412052" },
  { email: "haroon.rashid@zameen.com", name: "Haroon Rashid", title: "Director Projects", roles: ["HOD", "PM_USER"], entity: "ZD", department: "PROJ", phone: "+92 306 8412060" },
  { email: "aliya.zafar@zameen.com", name: "Aliya Zafar", title: "Project Manager — Opal Mall", roles: ["PM_USER"], entity: "ZD", department: "PROJ", phone: "+92 306 8412061" },
  { email: "raza.hussain@zameen.com", name: "Raza Hussain", title: "Project Manager — Park View Tower", roles: ["PM_USER"], entity: "ZD", department: "PROJ", phone: "+92 306 8412062" },
  { email: "nauman.ashraf@zameen.com", name: "Nauman Ashraf", title: "Head of Design & Architecture", roles: ["HOD", "DESIGN_USER"], entity: "ZD", department: "DESIGN", phone: "+92 306 8412063" },
  { email: "sadia.rehman@zameen.com", name: "Sadia Rehman", title: "Senior Architect", roles: ["DESIGN_USER"], entity: "ZD", department: "DESIGN", phone: "+92 306 8412064" },
  { email: "kashif.mehmood@zameen.com", name: "Kashif Mehmood", title: "MEP Manager", roles: ["HOD", "TECHNICAL_INSPECTOR"], entity: "ZD", department: "MEP", phone: "+92 306 8412065" },
  { email: "arsalan.baig@zameen.com", name: "Arsalan Baig", title: "Quantity Surveyor", roles: ["HOD", "REQUESTER"], entity: "ZD", department: "QS", phone: "+92 306 8412066" },
  { email: "zeeshan.qadir@zameen.com", name: "Zeeshan Qadir", title: "Civil QC Engineer", roles: ["TECHNICAL_INSPECTOR"], entity: "ZD", department: "PROJ", phone: "+92 306 8412067" },

  // ── ZD stores ─────────────────────────────────────────────
  { email: "iftikhar.hussain@zameen.com", name: "Iftikhar Hussain", title: "Warehouse Manager — Multan Road", roles: ["WAREHOUSE_MANAGER"], entity: "ZD", department: "SCM", phone: "+92 307 8412070" },
  { email: "naveed.anjum@zameen.com", name: "Naveed Anjum", title: "Site Store Incharge — Opal Mall", roles: ["SITE_STORE_USER", "STORE_MANAGER"], entity: "ZD", department: "SCM", phone: "+92 307 8412071" },
  { email: "ahsan.iqbal@zameen.com", name: "Ahsan Iqbal", title: "Site Store Incharge — Park View", roles: ["SITE_STORE_USER"], entity: "ZD", department: "SCM", phone: "+92 307 8412072" },
  { email: "shoaib.akram@zameen.com", name: "Shoaib Akram", title: "Site Store Incharge — Residencia", roles: ["SITE_STORE_USER"], entity: "ZD", department: "SCM", phone: "+92 307 8412073" },
  { email: "zd.admin@zameen.com", name: "Salman Yousaf", title: "Admin Manager — ZD", roles: ["ADMIN_FLOOR_MANAGER", "HOD"], entity: "ZD", department: "ADMIN", phone: "+92 307 8412074" },
];

export type SeedVendor = {
  code?: string;
  name: string;
  legalName: string;
  businessType: string;
  city: string;
  address: string;
  contactPerson: string;
  contactPhone: string;
  contactEmail: string;
  taxStatus: string;
  ntn: string;
  strn?: string;
  officeCount: number;
  citiesCovered: string;
  workforceCount: number;
  hasTransportation: boolean;
  supportStaffCount?: number;
  paymentTerms: string;
  creditDays: number;
  bankName: string;
  bankAccountTitle: string;
  bankAccountNumber: string;
  productsServices: string;
  categories: string;
  sourceChannel: string;
  status: string;
  isTrader?: boolean;
  minimumOrderValue?: number;
  entities: Array<"ZM" | "ZD">;
  /** 0..3 per criterion; drives the seeded evaluation. */
  scoreProfile: "excellent" | "strong" | "average" | "weak";
  references?: string;
};

export const VENDORS: SeedVendor[] = [
  {
    name: "Techno Solutions",
    legalName: "Techno Solutions (Pvt) Ltd",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "12-A, Hall Road, Lahore",
    contactPerson: "Mohsin Raza",
    contactPhone: "+92 42 3722 1100",
    contactEmail: "sales@technosolutions.pk",
    taxStatus: "FILER",
    ntn: "1234567-8",
    strn: "0300123456789",
    officeCount: 4,
    citiesCovered: "Lahore, Karachi, Islamabad, Faisalabad",
    workforceCount: 68,
    hasTransportation: true,
    supportStaffCount: 12,
    paymentTerms: "30 days from invoice",
    creditDays: 30,
    bankName: "Habib Bank Limited",
    bankAccountTitle: "Techno Solutions Pvt Ltd",
    bankAccountNumber: "01234567890123",
    productsServices: "Laptops, desktops, servers, networking, printers, UPS systems",
    categories: "IT-EQUIP, IT-PERIPH",
    sourceChannel: "REFERENCE",
    status: "APPROVED",
    entities: ["ZM", "ZD"],
    scoreProfile: "excellent",
    references: "Systems Ltd, Netsol Technologies, Bank Alfalah",
  },
  {
    name: "Digital World Computers",
    legalName: "Digital World Computers",
    businessType: "RETAILER",
    city: "Lahore",
    address: "Hafeez Centre, Shop 210, Gulberg III, Lahore",
    contactPerson: "Kashif Latif",
    contactPhone: "+92 42 3587 4400",
    contactEmail: "info@digitalworld.com.pk",
    taxStatus: "FILER",
    ntn: "2345678-9",
    strn: "0300234567890",
    officeCount: 2,
    citiesCovered: "Lahore, Islamabad",
    workforceCount: 24,
    hasTransportation: true,
    supportStaffCount: 5,
    paymentTerms: "15 days from invoice",
    creditDays: 15,
    bankName: "Meezan Bank",
    bankAccountTitle: "Digital World Computers",
    bankAccountNumber: "02345678901234",
    productsServices: "Laptops, monitors, peripherals, accessories",
    categories: "IT-EQUIP, IT-PERIPH",
    sourceChannel: "MARKET",
    status: "APPROVED",
    entities: ["ZM"],
    scoreProfile: "average",
  },
  {
    name: "Corporate IT Traders",
    legalName: "Corporate IT Traders",
    businessType: "TRADER",
    city: "Lahore",
    address: "Office 4, Beadon Road, Lahore",
    contactPerson: "Faisal Nadeem",
    contactPhone: "+92 42 3630 9900",
    contactEmail: "faisal@corporateittraders.pk",
    taxStatus: "NON_FILER",
    ntn: "3456789-0",
    officeCount: 1,
    citiesCovered: "Lahore",
    workforceCount: 8,
    hasTransportation: false,
    paymentTerms: "Advance / cash",
    creditDays: 0,
    bankName: "Bank Alfalah",
    bankAccountTitle: "Corporate IT Traders",
    bankAccountNumber: "03456789012345",
    productsServices: "Small-quantity IT hardware, spares, refurbished units",
    categories: "IT-EQUIP, IT-PERIPH",
    sourceChannel: "MARKET",
    status: "CONDITIONAL",
    isTrader: true,
    entities: ["ZM"],
    scoreProfile: "weak",
  },
  {
    name: "Amreli Steels Distributor — Steel Line",
    legalName: "Steel Line Trading Company",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Badami Bagh Iron Market, Lahore",
    contactPerson: "Aftab Sheikh",
    contactPhone: "+92 42 3766 5500",
    contactEmail: "orders@steelline.com.pk",
    taxStatus: "FILER",
    ntn: "4567890-1",
    strn: "0300456789012",
    officeCount: 3,
    citiesCovered: "Lahore, Gujranwala, Faisalabad",
    workforceCount: 55,
    hasTransportation: true,
    supportStaffCount: 8,
    paymentTerms: "30 days, 2% early settlement discount",
    creditDays: 30,
    bankName: "United Bank Limited",
    bankAccountTitle: "Steel Line Trading Company",
    bankAccountNumber: "04567890123456",
    productsServices: "Deformed steel bars grade 40/60, binding wire, structural steel",
    categories: "CONSTR-STEEL",
    sourceChannel: "REFERENCE",
    status: "APPROVED",
    entities: ["ZD"],
    scoreProfile: "excellent",
    references: "Habib Construction, Izhar Group, NLC",
  },
  {
    name: "Mughal Steel Direct",
    legalName: "Mughal Iron & Steel Industries Ltd — Direct Sales",
    businessType: "MANUFACTURER",
    city: "Lahore",
    address: "17-A, Off Sharaqpur Road, Lahore",
    contactPerson: "Hamza Mughal",
    contactPhone: "+92 42 3799 1200",
    contactEmail: "sales@mughalsteel.com",
    taxStatus: "FILER",
    ntn: "5678901-2",
    strn: "0300567890123",
    officeCount: 5,
    citiesCovered: "Nationwide",
    workforceCount: 1200,
    hasTransportation: true,
    supportStaffCount: 40,
    paymentTerms: "Advance against proforma, or 15 days with security",
    creditDays: 15,
    bankName: "Standard Chartered",
    bankAccountTitle: "Mughal Iron & Steel Industries Ltd",
    bankAccountNumber: "05678901234567",
    productsServices: "Rebar grade 60, girders, T-iron, billets",
    categories: "CONSTR-STEEL",
    sourceChannel: "MARKET",
    status: "APPROVED",
    entities: ["ZD"],
    scoreProfile: "strong",
  },
  {
    name: "Ittehad Steel Traders",
    legalName: "Ittehad Steel Traders",
    businessType: "TRADER",
    city: "Lahore",
    address: "Shop 88, Badami Bagh, Lahore",
    contactPerson: "Nasir Butt",
    contactPhone: "+92 42 3765 3311",
    contactEmail: "ittehadsteel@gmail.com",
    taxStatus: "NON_FILER",
    ntn: "6789012-3",
    officeCount: 1,
    citiesCovered: "Lahore",
    workforceCount: 12,
    hasTransportation: true,
    paymentTerms: "Cash on delivery",
    creditDays: 0,
    bankName: "Askari Bank",
    bankAccountTitle: "Ittehad Steel Traders",
    bankAccountNumber: "06789012345678",
    productsServices: "Small-lot rebar, cut & bend, binding wire",
    categories: "CONSTR-STEEL",
    sourceChannel: "MARKET",
    status: "APPROVED",
    isTrader: true,
    minimumOrderValue: 50000,
    entities: ["ZD"],
    scoreProfile: "average",
  },
  {
    name: "Maple Leaf Cement Dealer — Bilal Traders",
    legalName: "Bilal Traders",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Thokar Niaz Baig, Multan Road, Lahore",
    contactPerson: "Bilal Ahmed",
    contactPhone: "+92 42 3781 4422",
    contactEmail: "bilaltraders.cement@gmail.com",
    taxStatus: "FILER",
    ntn: "7890123-4",
    strn: "0300789012345",
    officeCount: 2,
    citiesCovered: "Lahore, Sheikhupura",
    workforceCount: 30,
    hasTransportation: true,
    supportStaffCount: 4,
    paymentTerms: "21 days",
    creditDays: 21,
    bankName: "Faysal Bank",
    bankAccountTitle: "Bilal Traders",
    bankAccountNumber: "07890123456789",
    productsServices: "OPC and SRC cement, sand, crush aggregate",
    categories: "CONSTR-CEMENT",
    sourceChannel: "REFERENCE",
    status: "APPROVED",
    entities: ["ZD"],
    scoreProfile: "strong",
  },
  {
    name: "Interwood Mobel",
    legalName: "Interwood Mobel (Pvt) Ltd",
    businessType: "MANUFACTURER",
    city: "Lahore",
    address: "Interwood Tower, Main Boulevard, Gulberg, Lahore",
    contactPerson: "Ammar Sohail",
    contactPhone: "+92 42 3577 8800",
    contactEmail: "corporate@interwood.pk",
    taxStatus: "FILER",
    ntn: "8901234-5",
    strn: "0300890123456",
    officeCount: 12,
    citiesCovered: "Nationwide",
    workforceCount: 900,
    hasTransportation: true,
    supportStaffCount: 60,
    paymentTerms: "50% advance, 50% on delivery",
    creditDays: 0,
    bankName: "Habib Metropolitan Bank",
    bankAccountTitle: "Interwood Mobel Pvt Ltd",
    bankAccountNumber: "08901234567890",
    productsServices: "Office furniture, workstations, chairs, conference tables, fit-out joinery",
    categories: "FURN, FITOUT",
    sourceChannel: "MEDIA",
    status: "APPROVED",
    entities: ["ZM", "ZD"],
    scoreProfile: "excellent",
  },
  {
    name: "Master Office Furnishers",
    legalName: "Master Office Furnishers",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Ferozepur Road, Lahore",
    contactPerson: "Waseem Anwar",
    contactPhone: "+92 42 3588 2211",
    contactEmail: "sales@masterfurnishers.pk",
    taxStatus: "FILER",
    ntn: "9012345-6",
    officeCount: 2,
    citiesCovered: "Lahore, Multan",
    workforceCount: 40,
    hasTransportation: true,
    paymentTerms: "30 days",
    creditDays: 30,
    bankName: "Bank of Punjab",
    bankAccountTitle: "Master Office Furnishers",
    bankAccountNumber: "09012345678901",
    productsServices: "Office chairs, desks, storage, partitions",
    categories: "FURN",
    sourceChannel: "WALK_IN",
    status: "APPROVED",
    entities: ["ZM", "ZD"],
    scoreProfile: "average",
  },
  {
    name: "Cool Air Engineering",
    legalName: "Cool Air Engineering Services",
    businessType: "CONTRACTOR",
    city: "Lahore",
    address: "45-C, Shadman II, Lahore",
    contactPerson: "Rizwan Haider",
    contactPhone: "+92 42 3757 6600",
    contactEmail: "projects@coolair.pk",
    taxStatus: "FILER",
    ntn: "0123456-7",
    strn: "0300012345678",
    officeCount: 2,
    citiesCovered: "Lahore, Islamabad",
    workforceCount: 85,
    hasTransportation: true,
    supportStaffCount: 22,
    paymentTerms: "30 days from commissioning",
    creditDays: 30,
    bankName: "MCB Bank",
    bankAccountTitle: "Cool Air Engineering Services",
    bankAccountNumber: "10123456789012",
    productsServices: "Split and cassette air conditioners, chillers, HVAC installation and AMC",
    categories: "HVAC",
    sourceChannel: "REFERENCE",
    status: "APPROVED",
    entities: ["ZM", "ZD"],
    scoreProfile: "strong",
  },
  {
    name: "Breeze Cooling Systems",
    legalName: "Breeze Cooling Systems",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Township, Lahore",
    contactPerson: "Sajid Mehmood",
    contactPhone: "+92 42 3511 9977",
    contactEmail: "sales@breezecooling.pk",
    taxStatus: "FILER",
    ntn: "1122334-5",
    officeCount: 1,
    citiesCovered: "Lahore",
    workforceCount: 26,
    hasTransportation: true,
    paymentTerms: "Advance",
    creditDays: 0,
    bankName: "Allied Bank",
    bankAccountTitle: "Breeze Cooling Systems",
    bankAccountNumber: "11223344556677",
    productsServices: "Air conditioners, refrigeration, installation",
    categories: "HVAC",
    sourceChannel: "INTERNET",
    status: "APPROVED",
    entities: ["ZM"],
    scoreProfile: "average",
  },
  {
    name: "Al-Noor Stationers",
    legalName: "Al-Noor Stationers & Printers",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Urdu Bazaar, Lahore",
    contactPerson: "Noor Muhammad",
    contactPhone: "+92 42 3712 3344",
    contactEmail: "alnoorstationers@gmail.com",
    taxStatus: "FILER",
    ntn: "2233445-6",
    officeCount: 1,
    citiesCovered: "Lahore",
    workforceCount: 18,
    hasTransportation: true,
    paymentTerms: "30 days",
    creditDays: 30,
    bankName: "Bank Al Habib",
    bankAccountTitle: "Al-Noor Stationers & Printers",
    bankAccountNumber: "22334455667788",
    productsServices: "Office stationery, paper, printing, pantry supplies",
    categories: "OFF-SUPPLY, PANTRY, MKT-MAT",
    sourceChannel: "RELATIONSHIP",
    status: "APPROVED",
    entities: ["ZM", "ZD"],
    scoreProfile: "strong",
  },
  {
    name: "Paper Plus Supplies",
    legalName: "Paper Plus Supplies",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Garden Town, Lahore",
    contactPerson: "Shahzad Aslam",
    contactPhone: "+92 42 3584 1122",
    contactEmail: "orders@paperplus.pk",
    taxStatus: "FILER",
    ntn: "3344556-7",
    officeCount: 1,
    citiesCovered: "Lahore",
    workforceCount: 14,
    hasTransportation: true,
    paymentTerms: "15 days",
    creditDays: 15,
    bankName: "Soneri Bank",
    bankAccountTitle: "Paper Plus Supplies",
    bankAccountNumber: "33445566778899",
    productsServices: "Copier paper, toners, office consumables",
    categories: "OFF-SUPPLY, IT-PERIPH",
    sourceChannel: "EMAIL",
    status: "APPROVED",
    entities: ["ZM"],
    scoreProfile: "average",
  },
  {
    name: "Signature Print Media",
    legalName: "Signature Print Media",
    businessType: "SERVICE_PROVIDER",
    city: "Lahore",
    address: "Johar Town, Lahore",
    contactPerson: "Talha Sultan",
    contactPhone: "+92 42 3531 7788",
    contactEmail: "hello@signatureprint.pk",
    taxStatus: "FILER",
    ntn: "4455667-8",
    strn: "0300445566778",
    officeCount: 2,
    citiesCovered: "Lahore, Islamabad",
    workforceCount: 45,
    hasTransportation: true,
    supportStaffCount: 9,
    paymentTerms: "50% advance, balance on delivery",
    creditDays: 7,
    bankName: "JS Bank",
    bankAccountTitle: "Signature Print Media",
    bankAccountNumber: "44556677889900",
    productsServices: "Billboards, panaflex, brochures, standees, signage, vehicle branding",
    categories: "MKT-MAT",
    sourceChannel: "REFERENCE",
    status: "APPROVED",
    entities: ["ZM", "ZD"],
    scoreProfile: "strong",
  },
  {
    name: "Prime Electricals",
    legalName: "Prime Electricals & Engineering",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Brandreth Road, Lahore",
    contactPerson: "Zubair Sattar",
    contactPhone: "+92 42 3763 2211",
    contactEmail: "sales@primeelectricals.pk",
    taxStatus: "FILER",
    ntn: "5566778-9",
    strn: "0300556677889",
    officeCount: 2,
    citiesCovered: "Lahore, Faisalabad",
    workforceCount: 38,
    hasTransportation: true,
    supportStaffCount: 6,
    paymentTerms: "30 days",
    creditDays: 30,
    bankName: "Askari Bank",
    bankAccountTitle: "Prime Electricals & Engineering",
    bankAccountNumber: "55667788990011",
    productsServices: "Cables, distribution boards, switchgear, lighting, MEP materials",
    categories: "MEP-ELEC, MEP-PLUMB",
    sourceChannel: "REFERENCE",
    status: "APPROVED",
    entities: ["ZD"],
    scoreProfile: "strong",
  },
  {
    name: "Bright Build Materials",
    legalName: "Bright Build Materials",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Raiwind Road, Lahore",
    contactPerson: "Adnan Shah",
    contactPhone: "+92 42 3595 4433",
    contactEmail: "info@brightbuild.pk",
    taxStatus: "FILER",
    ntn: "6677889-0",
    officeCount: 1,
    citiesCovered: "Lahore",
    workforceCount: 22,
    hasTransportation: true,
    paymentTerms: "21 days",
    creditDays: 21,
    bankName: "Summit Bank",
    bankAccountTitle: "Bright Build Materials",
    bankAccountNumber: "66778899001122",
    productsServices: "Tiles, gypsum board, paint, fit-out finishes",
    categories: "FITOUT, CONSTR-BLOCK",
    sourceChannel: "WALK_IN",
    status: "APPROVED",
    entities: ["ZD"],
    scoreProfile: "average",
  },
  {
    name: "Falcon Safety Supplies",
    legalName: "Falcon Safety Supplies",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Chauburji, Lahore",
    contactPerson: "Imtiaz Baig",
    contactPhone: "+92 42 3742 8899",
    contactEmail: "falconsafety@gmail.com",
    taxStatus: "FILER",
    ntn: "7788990-1",
    officeCount: 1,
    citiesCovered: "Lahore, Islamabad",
    workforceCount: 11,
    hasTransportation: false,
    paymentTerms: "15 days",
    creditDays: 15,
    bankName: "Bank Alfalah",
    bankAccountTitle: "Falcon Safety Supplies",
    bankAccountNumber: "77889900112233",
    productsServices: "PPE, helmets, harnesses, safety signage",
    categories: "SAFETY",
    sourceChannel: "INTERNET",
    status: "APPROVED",
    entities: ["ZD"],
    scoreProfile: "average",
  },
  {
    name: "Zenith Trading Company",
    legalName: "Zenith Trading Company",
    businessType: "TRADER",
    city: "Lahore",
    address: "Shahalam Market, Lahore",
    contactPerson: "Arif Chaudhry",
    contactPhone: "+92 42 3721 6655",
    contactEmail: "zenithtrading.lhr@gmail.com",
    taxStatus: "NON_FILER",
    ntn: "8899001-2",
    officeCount: 1,
    citiesCovered: "Lahore",
    workforceCount: 6,
    hasTransportation: false,
    paymentTerms: "Advance",
    creditDays: 0,
    bankName: "First Women Bank",
    bankAccountTitle: "Zenith Trading Company",
    bankAccountNumber: "88990011223344",
    productsServices: "General merchandise, office items, miscellaneous supply",
    categories: "OFF-SUPPLY, FURN",
    sourceChannel: "WALK_IN",
    status: "BLACKLISTED",
    entities: ["ZM"],
    scoreProfile: "weak",
  },
  {
    name: "Horizon Generators",
    legalName: "Horizon Power Systems",
    businessType: "DISTRIBUTOR",
    city: "Lahore",
    address: "Kot Lakhpat Industrial Area, Lahore",
    contactPerson: "Salman Chattha",
    contactPhone: "+92 42 3512 4400",
    contactEmail: "sales@horizonpower.pk",
    taxStatus: "FILER",
    ntn: "9900112-3",
    strn: "0300990011223",
    officeCount: 3,
    citiesCovered: "Lahore, Karachi, Islamabad",
    workforceCount: 74,
    hasTransportation: true,
    supportStaffCount: 20,
    paymentTerms: "30% advance, balance on commissioning",
    creditDays: 15,
    bankName: "Habib Bank Limited",
    bankAccountTitle: "Horizon Power Systems",
    bankAccountNumber: "99001122334455",
    productsServices: "Diesel generators, ATS panels, generator AMC",
    categories: "MACHINERY",
    sourceChannel: "REFERENCE",
    status: "APPROVED",
    entities: ["ZD"],
    scoreProfile: "strong",
  },
  {
    name: "Metro Office Systems",
    legalName: "Metro Office Systems",
    businessType: "DISTRIBUTOR",
    city: "Karachi",
    address: "Shahrah-e-Faisal, Karachi",
    contactPerson: "Yasir Kamal",
    contactPhone: "+92 21 3455 6677",
    contactEmail: "info@metrooffice.pk",
    taxStatus: "FILER",
    ntn: "1010101-1",
    officeCount: 2,
    citiesCovered: "Karachi, Hyderabad",
    workforceCount: 20,
    hasTransportation: true,
    paymentTerms: "30 days",
    creditDays: 30,
    bankName: "Meezan Bank",
    bankAccountTitle: "Metro Office Systems",
    bankAccountNumber: "10101010101010",
    productsServices: "Printers, copiers, office automation, consumables",
    categories: "IT-EQUIP, IT-PERIPH",
    sourceChannel: "INTERNET",
    status: "UNDER_EVALUATION",
    entities: ["ZM"],
    scoreProfile: "average",
  },
  {
    name: "Sunrise Interiors",
    legalName: "Sunrise Interiors & Contracting",
    businessType: "CONTRACTOR",
    city: "Lahore",
    address: "DHA Phase 5, Lahore",
    contactPerson: "Hassan Javed",
    contactPhone: "+92 42 3789 1010",
    contactEmail: "projects@sunriseinteriors.pk",
    taxStatus: "FILER",
    ntn: "1212121-2",
    officeCount: 1,
    citiesCovered: "Lahore",
    workforceCount: 65,
    hasTransportation: true,
    paymentTerms: "Milestone based",
    creditDays: 0,
    bankName: "Bank Alfalah",
    bankAccountTitle: "Sunrise Interiors & Contracting",
    bankAccountNumber: "12121212121212",
    productsServices: "Interior fit-out, false ceiling, partitions, joinery",
    categories: "FITOUT",
    sourceChannel: "REFERENCE",
    status: "PROSPECT",
    entities: ["ZD"],
    scoreProfile: "strong",
  },
];

/** Score value per criterion group by vendor profile (0..3). */
export const SCORE_PROFILES: Record<SeedVendor["scoreProfile"], (seq: number) => number> = {
  excellent: (seq) => (seq % 7 === 0 ? 2 : 3),
  strong: (seq) => (seq % 4 === 0 ? 2 : seq % 9 === 0 ? 1 : 3),
  average: (seq) => (seq % 3 === 0 ? 1 : 2),
  weak: (seq) => (seq % 4 === 0 ? 0 : 1),
};
