/**
 * Seeds the control calendar from the recurring obligations in ZAM/PUR/SOP-01.
 *
 *   npx tsx scripts/seed-controls.ts
 *
 * Every row cites the clause it comes from. A control the SOP does not require
 * is not here, and a control the SOP requires but the system cannot yet observe
 * is here marked `awaitingRollout` — visible as something the calendar is not
 * doing, rather than quietly absent.
 *
 * Idempotent.
 */
import { prisma } from "../src/lib/db";
import { systemActor } from "../src/lib/actor";
import { rollControlCalendar } from "../src/server/controls";

type Row = {
  code: string;
  name: string;
  description: string;
  frequency: "DAILY" | "WEEKLY" | "MONTHLY" | "QUARTERLY" | "HALF_YEARLY" | "ANNUAL";
  ownerRoleCode: string | null;
  graceDays: number;
  actionUrl: string | null;
  sourceReference: string;
  awaitingRollout?: boolean;
};

const CONTROLS: Row[] = [
  {
    code: "STORE-AUDIT",
    name: "Internal audit of the store",
    description:
      "A physical check of stock and inventory status against the ledger. The system's stock count sheets are the evidence for this control.",
    frequency: "MONTHLY",
    ownerRoleCode: "AUDIT_USER",
    graceDays: 7,
    actionUrl: "/inventory/counts",
    sourceReference:
      "ZAM/PUR/SOP-01 — 'Internal auditor audits the store on monthly basis, to monitor stock and inventory status.'",
  },
  {
    code: "MONTHLY-REQ-IT",
    name: "Monthly repeat requisition — IT equipment and accessories",
    description:
      "Projected requirements for the coming month compiled into a requisition, to carry reserve stock and avoid stock-out.",
    frequency: "MONTHLY",
    ownerRoleCode: "PROCUREMENT_OFFICER",
    graceDays: 3,
    actionUrl: "/requirements",
    sourceReference:
      "ZAM/PUR/SOP-01 §4.1 — requisitions generated by procurement for IT equipment",
  },
  {
    code: "MONTHLY-REQ-GH",
    name: "Monthly repeat requisition — grocery and housekeeping",
    description:
      "The logistics team's monthly compilation for general supplies: grocery, housekeeping, stationery and IT accessories.",
    frequency: "MONTHLY",
    ownerRoleCode: "WAREHOUSE_MANAGER",
    graceDays: 3,
    actionUrl: "/requirements",
    sourceReference:
      "ZAM/PUR/SOP-01 §4.1 — requisitions generated by the logistics team for grocery and housekeeping",
  },
  {
    code: "VENDOR-EVAL",
    name: "Supplier evaluation review",
    description:
      "Review of supplier evaluation results, so only fully qualified suppliers of specific fields are retained.",
    frequency: "QUARTERLY",
    ownerRoleCode: "PROCUREMENT_SENIOR_MANAGER",
    graceDays: 14,
    actionUrl: "/vendors/performance",
    sourceReference:
      "ZAM/PUR/SOP-01 CPC ToR — 'A mechanism to evaluate suppliers as per management objectives and review of the supplier evaluation results'",
  },
  {
    code: "PQ-EXPIRY-REVIEW",
    name: "Pre-qualification expiry review",
    description:
      "Which vendor pre-qualifications have lapsed or are about to, so requalification is prompted by a calendar rather than by a blocked requisition.",
    frequency: "QUARTERLY",
    ownerRoleCode: "PROCUREMENT_OFFICER",
    graceDays: 14,
    actionUrl: "/vendors/prequalification/validity",
    sourceReference: "Meeting requirement 20 — vendor PQ expiry and requalification",
  },
  {
    code: "MIN-STOCK-REVIEW",
    name: "Minimum stock level review",
    description:
      "The stock list and its minimum levels, checked against consumption history or POC advice.",
    frequency: "QUARTERLY",
    ownerRoleCode: "WAREHOUSE_MANAGER",
    graceDays: 14,
    actionUrl: "/inventory/replenishment",
    sourceReference:
      "ZAM/PUR/SOP-01 §3.3 — Manager Logistics maintains the stock list with minimum stock level defined from past consumption or POC advice",
  },
  {
    code: "AGEING-REVIEW",
    name: "Inventory ageing and expiry review",
    description:
      "Stock held over a year, stock that has not moved, and stock approaching or past its expiry date.",
    frequency: "MONTHLY",
    ownerRoleCode: "WAREHOUSE_MANAGER",
    graceDays: 7,
    actionUrl: "/inventory/ageing",
    sourceReference:
      "Meeting requirements — inventory ageing and expiry alerts. Not stated as a period in ZAM/PUR/SOP-01; monthly matches the store audit it supports.",
  },
  {
    code: "PAYMENT-PACK-REVIEW",
    name: "Annexure A document pack review",
    description:
      "Invoices handed to finance without their full Annexure A set, while the enforcement flag is still off.",
    frequency: "MONTHLY",
    ownerRoleCode: "PROCUREMENT_OFFICER",
    graceDays: 5,
    actionUrl: "/invoices",
    sourceReference:
      "ZAM/PUR/SOP-01 §3.4 — procurement ensures the supporting documents are available as per Annexure A",
  },
  {
    code: "ACCESS-REVIEW",
    name: "User access review",
    description:
      "Who holds which permissions, reviewed as a decision record rather than a report nobody signs.",
    frequency: "QUARTERLY",
    ownerRoleCode: "SYSTEM_ADMIN",
    graceDays: 21,
    actionUrl: "/admin/users",
    sourceReference:
      "Meeting requirements — quarterly access review as a decision record. Not in ZAM/PUR/SOP-01.",
    // The review needs somewhere to record the decision, and that screen does
    // not exist yet. Listed rather than run, so the calendar shows the gap.
    awaitingRollout: true,
  },
  {
    code: "SOD-REVIEW",
    name: "Segregation of duties review",
    description:
      "Whether anybody holds a combination of permissions the separations are meant to keep apart.",
    frequency: "HALF_YEARLY",
    ownerRoleCode: "AUDIT_USER",
    graceDays: 21,
    actionUrl: "/admin/roles",
    sourceReference:
      "Meeting requirements — segregation-of-duties configuration and report. The three per-transaction separations are enforced; the standing report is not built.",
    awaitingRollout: true,
  },
];

async function main() {
  let written = 0;
  for (const row of CONTROLS) {
    const data = {
      name: row.name,
      description: row.description,
      frequency: row.frequency,
      ownerRoleCode: row.ownerRoleCode,
      graceDays: row.graceDays,
      actionUrl: row.actionUrl,
      sourceReference: row.sourceReference,
      active: true,
      awaitingRollout: row.awaitingRollout ?? false,
    };
    const existing = await prisma.controlDefinition.findUnique({ where: { code: row.code } });
    if (existing) {
      await prisma.controlDefinition.update({ where: { id: existing.id }, data });
    } else {
      await prisma.controlDefinition.create({ data: { ...data, code: row.code } });
    }
    written += 1;
    console.log(
      `  ${row.frequency.padEnd(12)} ${row.code.padEnd(22)} ${row.ownerRoleCode ?? "unassigned"}${row.awaitingRollout ? "  [awaiting rollout]" : ""}`,
    );
  }

  console.log(`\n${written} control definitions written.`);

  const rolled = await rollControlCalendar(systemActor("SEED"));
  console.log(
    `Calendar rolled: ${rolled.opened} run(s) opened for the current period, ${rolled.missed} marked missed.`,
  );

  const awaiting = CONTROLS.filter((c) => c.awaitingRollout);
  if (awaiting.length) {
    console.log(
      `\n${awaiting.length} control(s) are listed but not being run, because the screen they need does not exist yet:`,
    );
    for (const c of awaiting) console.log(`  ${c.code} — ${c.name}`);
    console.log("They appear on the calendar as awaiting rollout rather than being hidden.");
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
